        <div style="padding-top:10px;padding-bottom:0px">
			<a href="/user/oauth?login=facebook" class="btn btn-medium btn-block btn-facebook"  style='color:white;'>
				<i class="icon-facebook"></i> <span>Facebook</span>
			</a>
			<a href="/user/oauth?login=google" class="btn btn-medium btn-block btn-google"  style='color:white;'>
				<i class = "icon-google-plus"></i> <span>Google</span>
			</a>
			<a href="/user/oauth?login=yahoo" class="btn btn-medium btn-block btn-yahoo"  style='color:white;'>
				<i class = "icon-sm-yahoo icon-sign-blank"></i> <span>Yahoo</span>
			</a>
			<a href="/user/oauth?login=twitter" class="btn btn-medium btn-block btn-twitter"  style='color:white;'>
				<i class="icon-twitter"></i> <span>Twitter</span>
			</a>
        </div>
