<?php // v($this->featured); die();?>
<div class="col-md-12">
				
				<div class="breadcrumb">
					<span class="label label-warning"><?php echo t('hotness',1);?></span> 
					<span class="pull-right"></span>
				</div>
				<!--End breadcum-->
<ul class="thumbnails">
<?php 
/** feature story list : $this->featured**/
$key=0; // check for video is printed or not
foreach ($this->featured as $k=>$row):
	if($row['type']=='3'): //if video 
		$key=$k; //save index
	?>
	<li class="col-md-4 first-video">
		<?php 
		echo<<<END
					<object width="420" height="315">
					<param name="movie" value="http://www.youtube.com/v/{$row['ytid']}?version=3&amp;hl=en_US">
					</param>
					<param name="allowFullScreen" value="true"></param>
					<param name="allowscriptaccess" value="always"></param>
					<embed src="http://www.youtube.com/v/{$row['ytid']}?version=3&amp;hl=en_US" type="application/x-shockwave-flash" 
					width="420" height="315" allowscriptaccess="always" allowfullscreen="true"></embed></object>
END;
		
		?>
		<div class="featured-title">
		<div class="col-md-8"><a href="<?php echo node_link('story',$row);?>">
		  <h2 class="story-title"> <?php echo $row['name'];?></h2>
		  </a>
		  </div>
		  <div class="col-md-4">
		  	<i class="<?php echo get_icon('eye-open');?>"></i>
		  	<i class="<?php echo get_icon('comment');?>"></i>
		  	<?php if(!isset($row['isVoteUp']) ):?>
                                <a id ="vote_up" class="cl_ajax" votes=<?php echo $row['counter']['vote'];?>" data-sand-callbacks-metadata="vote_story_success" href="/user/relate?id=<?php echo $row['id'];?>&object=story&rt=1">
                                    <i class="<?php echo get_icon('thumbs-up');?>"
                                    title="Click de vote chuyen nay hoi bi net"></i>
                                </a>
                             <?php endif; ?>
            <span class="vote_up"><?php echo $row['counter']['vote'];?></span>
            
            	<?php if(!isset($row['isVoteDown'])):?>
                              <a id="vote_down" class="cl_ajax" votes=<?php echo $row['counter']['vd'];?>" data-sand-callbacks-metadata="vote_story_success" href="/user/relate?id=<?php echo $row['id'];?>&object=story&rt=4">
                                <i class="<?php echo get_icon('thumbs-down');?>"></i>
                                </a>
                               <?php endif;?>
             <span class="vote_down"><?php echo $row['counter']['vd'];?></span>
		  </div>
		</div>
		
		  
	</li>	
<?php 
break;
endif;
endforeach;
$maxValue=8;

if($key <8) $maxValue++;
foreach ($this->featured as $k=>$row ):
	
	if ($k<$maxValue && $k!=$key):
?>
					<!--need fix  video thumbail  size to 160*90 like Youtube-->
					<li class="col-md-2 featured">
					<?php 
					if(isset($row['type'])){
				if($row['type']==2){
					$imgLink = img_link($row['url']);
					echo<<<END
						<img src="{$imgLink}" width=100%></img>		
END;
				}
	elseif($row['type']==3){
					echo<<<END
					<object width="420" height="315">
					<param name="movie" value="http://www.youtube.com/v/{$row['ytid']}?version=3&amp;hl=en_US">
					</param>
					<param name="allowFullScreen" value="true"></param>
					<param name="allowscriptaccess" value="always"></param>
					<embed src="http://www.youtube.com/v/{$row['ytid']}?version=3&amp;hl=en_US" type="application/x-shockwave-flash" 
					width="420" height="315" allowscriptaccess="always" allowfullscreen="true"></embed></object>
END;
				}
	else $maxValue++;
				
			}
				
					
					?>
		<div class="col-md-12 featured-title small " ><a href="<?php echo node_link('story',$row);?>"><?php echo $row['name'];?></a></div>			
					</li>
						
			<!-- end span12-->
<?php 
endif;
endforeach;?>
	</ul>
			</div>
