<?php if (APPLICATION_ENV == 'development'):?>
<link href="<?php echo SAND_ASSETS_CDN;?>bootstrap-3.0.0/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="<?php echo SAND_ASSETS_CDN;?>/css/common.css" media="screen" rel="stylesheet" type="text/css" >
<link href="<?php echo ASSETS_CDN;?>/css/styles.css" media="screen" rel="stylesheet" type="text/css" >
<link href="<?php echo ASSETS_CDN;?>/css/vne.css" media="screen" rel="stylesheet" type="text/css" >
<link href="<?php echo SAND_ASSETS_CDN;?>/js/plugins/toastmessage/src/main/resources/css/jquery.toastmessage.css" rel="stylesheet" type="text/css"/>
<link rel="stylesheet" type="text/css" href="<?php echo SAND_ASSETS_CDN;?>/js/plugins/tokeninput/styles/token-input-facebook.css" />
<?php else:?>
    <link rel="stylesheet" type="text/css" href="<?php echo ASSETS_CDN;?>/css/all.css?v=<?php echo get_conf('js:version',1);?>"/>
<?php endif;?>
<?php
echo $this->headLink();
?>
