<?php 
$lu = Zend_Registry::get('user');
$theme = Zend_Registry::get('theme');
$cates = Dao_Node_Category::getInstance()->getByList('site:top_menu');
$categorySlugs = Zend_Registry::isRegistered('categorySlugs') ? Zend_Registry::get('categorySlugs') : array();
$page = Zend_Registry::get('page');
?>
<div class="navbar navbar-default navbar-fixed-top" id='user_menu'>
		<?php
		/* 
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/"><?php echo gen_icon('home');?></a>
        </div>
        */
		?>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav" id='left-main-menu' >
          		<?php 
/*
 * 
          		<li <?php if ($page == "story/index/index" && count($categorySlugs) == 0):?>class='active'<?php endif;?>><a href="/"><?php echo gen_icon('home');?></a></li>
 */          		
          		?>
				<li><a href="/"><?php echo gen_icon('home');?></a></li>          		
              	<?php 
              	foreach ($cates as $cate):?>
              	    <li <?php if (in_array($cate['slug'], $categorySlugs)):?>class='active'<?php endif;?>>
              	        <a class='menu-item' href='<?php echo node_link('category',$cate);?>'><?php echo $cate['name'];?></a>
              	    </li>
              	<?php endforeach;?>
              <?php
              /*
               * 
              <li><a title="Mobile" href="<?php echo MOBILE_URL;?>">
              <?echo gen_icon('mobile');?></a></li>
               */?>
		</ul>              
		<ul class="nav navbar-nav navbar-right" id='top-user-menu-right'>
                <li tabindex="-1" id='concept-search-li' class='hidden-sm'>
            		<div class="input-group">
                	 	<span class="input-group-addon"><a href='#'><?php echo gen_icon('search');?></a></span>
                	 	<input id='concept-search-input' 
                	 		type="text" 
                	 		tabindex="1" 
                	 		data-provide="typeahead" 
                            placeholder="Search: Enter keywords, e.g &quot;present tense&quot;" 
                            data-where='top-search-box'
                            class="input form-control" 
                            autocomplete="off" 
                            name="_q" 
                            style="width: 200px;">
					</div>                                    
				</li>
 			<li id='admin-menu' style='display:none;' 
 				class="dropdown hover  <?php if ($page == 'user/index/update' ):?>active<?php endif;?>">
               <a data-target="#" class="dropdown-toggle" data-toggle="dropdown" href='#'>
               	<?php echo gen_icon('cog');?>
                </a>
                	<ul class="dropdown-menu">
                   		    <li style="width:100%">
                    		      <a href="/story/admin"><?php echo gen_icon('cog');?> Admin
                    			   </a></li>
                		    <li style="width:100%">
                		    <a href="/story/new">
                			    <?php echo gen_icon('arrow-up');?> Upload</a></li>
                	</ul>
          	</li>
            </ul>
          </div><!--/.nav-collapse -->
    </div>
    

<div class='container top-menu-gap'></div>
<?php if (Zend_Registry::isRegistered('categorySlugs')  && count(Zend_Registry::get('categorySlugs')) > 0) :?>

<div class='container'>
<?php 
$subcategoryTree = $this->subcategoryTree;
$subCate = Zend_Registry::isRegistered('subcategory') ? Zend_Registry::get('subcategory') : '';
?>
<div class='row'>
	<div class='col-md-12'>
		<ul id='top_submenu' class='nav nav-pills'>
			<?php foreach ($subcategoryTree as $c):?>
				<li <?php if ($c['slug'] == $subCate):?>class="active"<?php endif;?>><a href="<?php echo node_link('category', $c);?>"><?php echo $c['name']?></a></li>
			<?php endforeach;?>
		</ul>		
	</div>
</div>

<?php if (Zend_Registry::isRegistered('categoryTreeLine')):?>
<?php 
$categoryTreeLine = Zend_Registry::get('categoryTreeLine');
$count = count($categoryTreeLine) - 1;
?>
<div class='row'>
	<div class='col-md-12'>
	<ul class='breadcrumb' id='top_cate_bread'>
		<?php foreach ($categoryTreeLine as $i => $c):?>
			<li <?php if ($i == $count):?>class='active'<?php endif;?>><a href="<?php echo node_link('category', $c);?>"><?php echo $c['name']?></a></li>
		<?php endforeach;?>
	</ul>
	</div>
</div>

<?php endif;?>
</div>
<?php endif;?>
    