<?php 
    $lu =  Zend_Registry::get('user');
    $page = 'home';
    if (isset($_REQUEST['page']))
        $page = $_REQUEST['page'];
    if (Zend_Registry::isRegistered('page'))
        $page = Zend_Registry::get('page');
    $theme = Zend_Registry::get('theme');

?>
<!DOCTYPE html>
<html>
	<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title><?php echo Bootstrap::$pageTitle;?></title>
    <meta name="description" content="<?php echo Bootstrap::$pageDesc;?>" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="">
    

    <?php echo $this->render('development-css.phtml');?>
<style>
div.navbar ul.breadcrumb > li
{
	min-height:30px;
	padding-top:10px;
}
</style>
<?php 
$format = "DD/MM/YYYY";
?>

<?php echo $this->render('widget/php-to-js.phtml');?>
<script type='text/javascript'>
CL.DATE_FORMAT = "<?php echo substr(strtolower($format), 0, -2);?>";
</script>
	
</head>
<body>
 
<?php echo $this->render("guest_menu.phtml");?>

<?php if (APPLICATION_ENV == 'development'):?>
<div class='sand-dev-info alert alert-info' style='display:none;'>
    <?php $p = explode('/', $page);?>
    <b>Action:</b> <?php echo $page;?> 
    <br/>
    <b>Layout script=WhereAmI:</b> <span class='sand-dev-selecttext' ><?php echo __FILE__;?></span>
    <br/>
    <b>Controller File:</b> <span class='sand-dev-selecttext'><? echo APPLICATION_PATH;?>/modules/<?php echo $p[0]?>/controllers/<?php echo ucwords($p[1])?>Controller.php</span>
</div>
<?php endif;?>


<div class='container' style='min-height:500px'>
     <?php echo $this->layout()->content; ?>
</div>


<div class='separator-high'>
</div>

<div class=''>
	<div class='col-md-12'>
	    <div class='well'>
	    <div class='separator'></div>
	    
        Copyright &copy; 2012 <strong>news.com</strong> <br/>
        
            <a href="/page/contact">Contact</a> · 
            <a href="/page/about-us.html">About Us</a> · 
            <a href="/page/privacy.html">Privacy</a> · 
            <a href="/page/terms.html">Terms Of Service</a> · 
            <a href="/page/help.html" title="Help on how to use the website">Help</a>
        </div> 
    </div>
</div>


<div id="ajaxModal" class="modal fade" 
    tabindex="-1" role="dialog" aria-labelledby="ajaxModalLabel" aria-hidden="true"
    role="dialog"
>  
    <div class="modal-dialog">
    	<div class="modal-content">
		    <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		        <h4 id="ajaxModalLabel"></h4>
		    </div>
		    
		    <div class="modal-body">
		    </div>
		    
		    <div class="modal-footer" style='display:none;'>
		        <button class="btn" data-dismiss="modal" aria-hidden="true"><?php echo t('close',1);?></button>
		        <button class="btn btn-primary" id="yes_help_thanks" ><i class='icon-ok'></i> <?php echo t('yes', 1);?></button>
		    </div>
	    </div>
    </div>
</div>

<?php echo $this->render('news-js.phtml');?>
        
<?php echo $this->headScript();?>
<?php print $this->inlineScript();?>
</body>
</html>

