<?php 
    $lu =  Zend_Registry::get('user');
    $page = 'home';
    if (isset($_REQUEST['page']))
        $page = $_REQUEST['page'];
    if (Zend_Registry::isRegistered('page'))
        $page = Zend_Registry::get('page');

?>
<!DOCTYPE html>
<html>
	<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title><?php echo Bootstrap::$pageTitle;?></title>
    <meta name="description" content="<?php echo Bootstrap::$pageDesc;?>" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="">
    

	<link href="<?php echo SAND_ASSETS_CDN;?>bootstrap-3.0.0/dist/css/bootstrap.min.css" rel="stylesheet">
	<?php
	/* 
    <link href="<?php //echo ASSETS_CDN;?>/font-awesome-3.2.1/css/font-awesome.css" rel="stylesheet">
    */
	?>
    <link href="<?php echo SAND_ASSETS_CDN;?>/css/common.css" media="screen" rel="stylesheet" type="text/css" >
	<link href="<?php echo ASSETS_CDN;?>/css/styles.css" media="screen" rel="stylesheet" type="text/css" >
    <link href="<?php echo SAND_ASSETS_CDN;?>/js/plugins/toastmessage/src/main/resources/css/jquery.toastmessage.css" rel="stylesheet" type="text/css"/>
    
    <link href="<?php echo ASSETS_CDN;?>/js/mm/mm.css" rel="stylesheet" type="text/css"/>
	
	<?php
    echo $this->headLink();
    ?>

<?php 
$format = "DD/MM/YYYY";
?>

<script type='text/javascript'>
<?php echo $this->render('widget/php-to-js.phtml');?>
CL.DATE_FORMAT = "<?php echo substr(strtolower($format), 0, -2);?>";
</script>
	
</head>
<body> 

<?php if (get_value('tinymce') != '1'):?>
	<?php echo $this->render("news.laichau.admin_menu.phtml");?>
	<div class='container' style='min-height:60px;'>
	</div>
<?php endif;?>

<div class='container' style='min-height:200px'>
     <?php echo $this->layout()->content; ?>
</div>

<?php //if (APPLICATION_ENV == 'development') :?>

    <script src="<?php echo SAND_ASSETS_CDN;?>/js/jquery.js"></script>
	<script src="<?php echo SAND_ASSETS_CDN;?>/js/plugins/toastmessage/src/main/javascript/jquery.toastmessage.js" type="text/javascript"></script>
	<script src="<?php echo SAND_ASSETS_CDN;?>/js/3rdparty/mustache.js" type="text/javascript"></script>
	<script src="<?php echo SAND_ASSETS_CDN;?>/js/sand/utils.js" type="text/javascript"></script>
    <script src="<?php echo SAND_ASSETS_CDN;?>/js/plugins/jquery.form.js" type="text/javascript"></script>
    
    <script type="text/javascript" src="<?php echo SAND_ASSETS_CDN;?>/js/plugins/tokeninput/src/jquery.tokeninput.js"></script>
    <link rel="stylesheet" type="text/css" href="<?php echo SAND_ASSETS_CDN;?>/js/plugins/tokeninput/styles/token-input-facebook.css" />
    <script src="<?php echo SAND_ASSETS_CDN;?>/js/sand/cl_ajax_metadata_config.js" type="text/javascript"></script>
    <?php /*<script type="text/javascript" src="<?php echo SAND_ASSETS_CDN;?>/js/tinymce/tinymce_3.5.2/jscripts/tiny_mce/tiny_mce.js"></script>*/?>
    <script type="text/javascript" src="<?php echo SITE_URL;?>/tinymce/js/tinymce/tinymce.min.js"></script>
    <script src="<?php echo ASSETS_CDN;?>/js/vi.js"></script>
	<script type="text/javascript" src="<?php echo ASSETS_CDN;?>/js/tinymce_init.js" type="text/javascript"></script>    
        
    <script src="<?php echo ASSETS_CDN;?>/js/site.js" type="text/javascript"></script>
    <script src="<?php echo SAND_ASSETS_CDN;?>/js/sand/comment.js" type="text/javascript"></script>
    
    <script src="<?php echo SAND_ASSETS_CDN;?>/js/sand/cl_ajax.js" type="text/javascript"></script>
    <script src="<?php echo SAND_ASSETS_CDN;?>/js/sand/site_common.js" type="text/javascript"></script>
    <script src="<?php echo SAND_ASSETS_CDN;?>/js/plugins/jquery.ui.datepicker.js" type="text/javascript"></script>
    <script src="<?php echo SAND_ASSETS_CDN;?>/js/plugins/autoresize.jquery.js" type="text/javascript"></script>
    
    
    <script src="<?php echo SAND_ASSETS_CDN;?>bootstrap-3.0.0/dist/js/bootstrap.min.js"></script>
	<script src="<?php echo SAND_ASSETS_CDN;?>js/3rdparty/typeahead.js/typeahead.js"></script>
	
	<script
		src="<?php echo SAND_ASSETS_CDN;?>/js/plugins/jquery.timeago.js"
		type="text/javascript"></script>
	
	<script type="text/javascript" src="<?php echo ASSETS_CDN;?>/js/mm/mm.js"></script>
		
	<?php echo $this->headScript();?>
	<?php print $this->inlineScript();?>
</body>
</html>

