<?php 
    $lu =  Zend_Registry::get('user');
    $page = 'home';
    if (isset($_REQUEST['page']))
        $page = $_REQUEST['page'];
    if (Zend_Registry::isRegistered('page'))
        $page = Zend_Registry::get('page');

?>
<!DOCTYPE html>
<html>
    <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title><?php echo Bootstrap::$pageTitle;?> - <?php echo get_conf('title_suffix', ':');?></title>
    <meta name="description" content="<?php echo Bootstrap::$pageDesc;?>" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="">
    

    <link href="<?php echo SAND_ASSETS_CDN;?>bootstrap-3.0.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="<?php //echo ASSETS_CDN;?>/font-awesome-3.2.1/css/font-awesome.css" rel="stylesheet">
    <link href="<?php echo SAND_ASSETS_CDN;?>/css/common.css" media="screen" rel="stylesheet" type="text/css" >
    <link href="<?php echo ASSETS_CDN;?>/css/nga.css" media="screen" rel="stylesheet" type="text/css" >
    <link href="<?php echo SAND_ASSETS_CDN;?>/js/plugins/toastmessage/src/main/resources/css/jquery.toastmessage.css" rel="stylesheet" type="text/css"/>
        <?php
    echo $this->headLink();
    ?>
        
<?php
/* 
//else 
//<link href="<?php echo ASSETS_CDN . "css/_v" . JSVERSION . ".css"?>" media="screen" rel="stylesheet" type="text/css" >
// endif;
 * 
 */
?>

<style>
div.navbar ul.breadcrumb > li
{
    min-height:30px;
    padding-top:10px;
}
</style>
<?php 
$format = "DD/MM/YYYY";
?>

<script type='text/javascript'>
<?php echo $this->render('widget/php-to-js.phtml');?>
CL.DATE_FORMAT = "<?php echo substr(strtolower($format), 0, -2);?>";
</script>
    
</head>
<body>

<?php
/* 
        <div>
            <img  class='img-responsive' style='width:100%;height:' 
                src='<?php echo ASSETS_CDN;?>/images/<?php echo getenv('SITE');?>/banner_top.jpg' />
        </div>
*/        
?>
        <div class="navbar navbar-default" id='user_menu'>
            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav" id='left-main-menu' >
                  <li <?php if ($_SERVER['REQUEST_URI'] == '/'):?>class='active'<?php endif;?>>
                    <a href="/">
                    <i class='<?php echo get_icon('home', $type = 'glyph');?>'></i> </a>
                  </li>
                      <?php 
                      $cateTree = Dao_Node_Category::getInstance()->getByList('top_menu');
                      $activeCate = Zend_Registry::isRegistered('category') ? 
                      	Zend_Registry::get('category') : ''; 
                      ?>

                      <?php foreach ($cateTree as $cate):?>
                            <li <?php if ($activeCate == $cate['slug']):?>class='active'<?php endif;?>>
                              	<a href='/<?php echo $cate['slug'];?>/'><?php echo $cate['name'];?></a>
                            </li>
                       <?php endforeach;?>
                      
                </ul>
              </div><!--/.nav-collapse -->
        </div>

<div class='container' style='min-height:500px'>
<?php echo $this->layout()->content; ?>
</div>


<div class='well well-xs' style='margin-bottom:0px;'>
        	<br/>
            <a href="/page/contact">Contact</a> · 
            <a href="/page/about-us.html">About Us</a> · 
            <a href="/page/privacy.html">Privacy</a> · 
            <a href="/page/terms.html">Terms Of Service</a> · 
            <a href="/page/help.html" title="Help on how to use the website">Help</a> .
            <a href="/user/login" title="Help on how to use the website">Login</a> .
            
            <a href="/site/admin" style='color:transparent;' rel='nofollow' title="">Qt</a>
</div> 

<?php echo $this->render('news-js.phtml');?>
<?php echo $this->headScript();?>
<?php print $this->inlineScript();?>

<div id="ajaxModal" class="modal hide fade modal-wrap" 
    tabindex="-1" role="dialog" aria-labelledby="ajaxModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="ajaxModalLabel"></h3>
    </div>
    
    <div class="modal-body">
    </div>
    
    <div class="modal-footer" style='display:none;'>
        <button class="btn" data-dismiss="modal" aria-hidden="true"><?php echo t('close',1);?></button>
        <button class="btn btn-primary" id="yes_help_thanks" ><i class='icon-ok'></i> <?php echo t('yes', 1);?></button>
    </div>
</div>

</body>
</html>

