<h1>Role List</h1>
<?php
echo ($this->form);
?>
<div style='clear:both'></div>
<?php if (isset($this->list) && count($this->list) > 0) :?>
<?php if($this->total > 0) :?>
    <?php echo $this->render("widget/pagination.phtml");?>
<?php endif;?>
<table>
<thead>
	<td>Name</td><td>Perms</td><td>action</td>
</thead>
<tbody>
	<?php foreach ($this->list as $row) :?>
	<tr>
	<td><b><?php echo $row['name']?></b></td>
	<td> <?php echo implode(", ", $row['permissions']);?></td>
	<td><a class='cl_ajax' data-sand-callbacks-metadata='hide_my_parent:2' href='/user/role/delete?id=<?php echo $row['id']?>'>delete</a> | <a href='/user/role/update?id=<?php echo $row['id']?>'>edit</a>
	</td>
	<?php endforeach;?>
</tbody>
</table>
<?php else:?>
No match
<?php endif;?>
<div style='clear:both'><hr/></div>
<a href='/user/role/new'>new role</a>