<?php $page = Zend_Registry::get('page');?>
<div class='border-style' style='margin-top: 10px;'>
<ul class='nav nav-pills nav-stacked'>
	<li <?php if ($page == 'template/index/new') echo "class='active';"?>><a href="/template/new"><?php echo gen_icon('plus');?>
	<?php if (!isset($this->compactMode)):?> New<?php endif;?></a></li>
	<? if (isset($this->row)) :?>    
	<li <?php if ($page == 'template/index/update') echo "class='active';"?>>
	<a href="/template/update<?php if (isset($this->row['id'])) echo "?id=" . $this->row['id'];?>"><?php echo gen_icon('edit');?>
	<?php if (!isset($this->compactMode)):?> Update<?php endif;?></a></li>
	<?php endif;?>    
	<li <?php if ($page == 'template/index/search') echo "class='active';"?>><a href="/template/search"><?php echo gen_icon('search');?>
	<?php if (!isset($this->compactMode)):?> Search<?php endif;?></a></li>
</ul>

<div style='min-height:10px;'></div>
</div>