<?php echo sand_dev_info_phtml(__FILE__);?>
<div class='row' >

	<?php $page = Zend_Registry::get('page');?>
	<div class='col-md-2'>
		<?php echo $this->render('index/navbar.phtml');?>
	</div>
	
	<div class='col-md-10'>
		<div class='row'>
			<div class='col-md-12'>
				<?php if ($page == 'template/index/update'):?>
				<h3> <?php echo t('update_template',1);?></h3>
				<?php else:?>
				<h3> <?php echo t('add_new_template',1);?></h3>
				<?php endif;?>
				<?php $this->form->setAttrib('class', 'cl_ajax');?>
				<?php echo $this->form;?>
			</div>
		</div>
</div>