<div class='row' >

<?php echo sand_dev_info_phtml(__FILE__);?>

<div class='col-md-1'>
<?php $this->compactMode = 1;?>
<?php echo $this->render('index/navbar.phtml');?>
</div>

<div class='col-md-2'>
    <div class='search_form well form-fit-width well-shallow'>
    <?php $this->form->setDisplayInline();
        $this->form->setAttrib('id' , 'search_form');
    ?>
    <?php echo $this->form;?>
    </div>
</div>

<div class='col-md-9'>
    <?php if($this->total > 0) :?>
        <?php echo $this->render("widget/pagination.phtml");?>
    <?php endif;?>
    
    <?php if($this->count > 0) :?>
	
    	<?php //echo $this->render('widget/table.phtml');?>
    	<a href="/template/bulk-delete" id='bulk-delete' class="cl_ajax btn btn-xs btn-danger"><i class='icon-remove'></i> Delete Selected</a>
    	<div class="clear"></div>
    	<br/>
        <table class="table table-striped table-bordered table-condensed">
        	<thead>
        		<tr>
        			<th style='width:10px;'><input type="checkbox" class="checkall"/></th>
        			<th  style='width:10%;'>Name</th>
        			<th style='width:10%;'>Lists</th>
        			<th style='width:10%;'>Themes</th>
        			<th>Layout</th>
        			<th style='width:5%;'>Action</th>
        		</tr>
        	</thead>
        	<tbody>
        		<?php foreach($this->list as $row) :?>
        		<?php 
        		if (!isset($row['avatar']) || $row['avatar'] == '')
        			$row['avatar'] = ASSETS_CDN . '/images/avatar.gif' ;
        		?>
        		<tr id="<?php echo $row['id'];?>">
        			<td><input type="checkbox" value="<?php echo $row['id'];?>" class="check-item" /></td>
        			<td>
        				<?php echo $row['name'];?>
        			</td>
        			<td>
        				<?php foreach ($row['lists'] as $l):?>
        				<div>
	        				<?php echo $l;?>
        				</div>
        				<?php endforeach;?>
        			</td>
        			<td>
    				<?php foreach ($row['themes'] as $l):?>
        				<div>
	        				<?php echo $l;?>
        				</div>
        				<?php endforeach;?>
            			
        			</td>
        			
        			<td>
	        			Layout Image
        			</td>
        			<td>
        				<a href="/template/update?id=<?php echo $row['id']?>" class="btn btn-default btn-xs"><i class="icon-edit"></i> Edit</a>
        				<a href="/template/delete?id=<?php echo $row['id']?>" 
        					class="btn btn-xs btn-danger cl_ajax" data-sand-callbacks-metadata="remove_my_parent:2"
        					data-sand-ajax-confirm='Are you sure you want to permanently delete this item?'
        					>
        					<i class="icon-remove"></i> Delete
        				</a>
        			</td>
        		</tr>
        		<?php endforeach;?>
        	</tbody>
        </table>
    <?php else:?>
    	<h3>No template found</h3>
    <?php endif;?>
</div>

</div>