<?php 
$userToSend = $this->userToSend;
$activity = $this->activity;

?>
Hello <b><?php echo $userToSend['name']?></b>,

<p> 
<b><a href='<?php echo get_user_link($activity['actor']['u'], true);?>'> 
@<?php echo $activity['actor']['u']['name']?> <a/></b> 
has commented "<?php echo $activity['object']['c']['name'];?> ..."
on 
<?php if ($this->notifType == 'comment_on_my_post') : ?> your post 
<?php else:?>
	post you commented on or you are following 
<?php endif;?>
<a href="<?php echo get_post_link($activity['context']['p'], true); echo '#'; echo $activity['object']['c']['id'];?>"><?php echo $activity['context']['p']['name']?></a>
</p>

<?php echo $this->render('/templates/notif/email-footer.phtml');?>
