<p><br/>
  Thank you </p>
<p>Stuffowners.com team</p>
<hr/>
<p>
    Do NOT reply to this email<br/>
    This is a <?php echo $this->type;?> digest of you and your friends activities on Stuffowners.com
    <br/>
    If you do not want to receive <?php echo $this->type;?> digests, please take a  moment to change
    your digest settings in <a href="<?php echo SITE_URL?>/user/update?_cl_step=digest">Digest settings</a>
    <br/>
    <b>Copyright © 2012 Stuffowners.com</b>
</p>
