<div class='row' >

<?php echo sand_dev_info_phtml(__FILE__);?>

<div class='col-md-1'>
<?php $this->compactMode = 1;?>
<?php echo $this->render('index/navbar.phtml');?>
</div>

<div class='col-md-2'>
    <div class='search_form well form-fit-width well-shallow'>
    <?php $this->form->setDisplayInline();
        $this->form->setAttrib('id' , 'search_form');
    ?>
    <?php echo $this->form;?>
    </div>
</div>

<div class='col-md-9'>
    <?php if($this->total > 0) :?>
        <?php echo $this->render("widget/pagination.phtml");?>
    <?php endif;?>
    
    <?php if($this->count > 0) :?>
	
    	<?php //echo $this->render('widget/table.phtml');?>
    	<a href="/source/bulk-delete" id='bulk-delete' class="cl_ajax btn btn-xs btn-danger"><i class='icon-remove'></i> Delete Selected</a>
    	<div class="clear"></div>
    	<br/>
        <table class="table table-striped table-bordered table-condensed">
        	<thead>
        		<tr>
        			<th><input type="checkbox" class="checkall"/></th>
        			<th>ava</th>
        			<th >Code</th>
        			<th >Name</th>
        			<th style='width:10%;'>Domains</th>
        			<th style='width:20%;'>Language/Country</th>
        			<th style='width:15%;'>Status</th>
        			<th style='width:5%;'>Action</th>
        		</tr>
        	</thead>
        	<tbody>
        		<?php foreach($this->list as $row) :?>
        		<?php 
        		if (!isset($row['avatar']) || $row['avatar'] == '')
        			$row['avatar'] = ASSETS_CDN . '/images/avatar.gif' ;
        		?>
        		<tr id="<?php echo $row['id'];?>">
        			<td><input type="checkbox" value="<?php echo $row['id'];?>" class="check-item" /></td>
        			<td>
        			<?php if (isset($row['avatar'])):?>
        			<a href="<?php echo $row['url'];?>">
        			<img class='img50 thumbnail' src='<?php echo $row['avatar'];?>'/></a>
        			<?php endif;?>
        			</td>
        			<td>
        				<?php echo $row['slug'];?>
        			</td>
        			<td><a class='modal_ajax preview_source' 
        				href="<?php echo $row['url'];?>">
        				<?php echo $row['name'];?></a>
        			    <p class='chapo' style='display:none;'><?php echo $row['chapo'];?></p>
        			</td>
        			
        			<td>
	        			<?php foreach ($row['domains'] as $d):?>
	        				<div>
	        				<?php echo $d;?>
	        				</div>
	        			<?php endforeach;?>
        			<td>
        			 <?php echo $row['language']?> / <?php echo $row['country']?>  
        			</td>
        			<td>
                        <div class="btn-group">
        			    	<a href="/source/update?id=<?php echo $row['id'];?>&status=0&_cl_step=status"
        			    	class="btn btn-primary btn-xs <?php if($row['status']==0) echo 'active';?> cl_ajax" 
        			    	data-sand-callbacks-metadata="active_button_group">Q.</a>
        			    	<a href="/source/update?id=<?php echo $row['id'];?>&status=1&_cl_step=status"
        			    	class="btn btn-primary btn-xs <?php if($row['status']==1) echo 'active';?> cl_ajax" data-sand-callbacks-metadata="active_button_group">Apprvd</a>
        			    </div>
        			</td>
        			
        			<td>
        				<a href="/source/update?id=<?php echo $row['id']?>" class="btn btn-default btn-xs"><i class="icon-edit"></i> Edit</a>
        				<a href="/source/delete?id=<?php echo $row['id']?>" 
        					class="btn btn-xs btn-danger cl_ajax" data-sand-callbacks-metadata="remove_my_parent:2"
        					data-sand-ajax-confirm='Are you sure you want to permanently delete this item?'
        					>
        					<i class="icon-remove"></i> Delete
        				</a>
        			</td>
        		</tr>
        		<?php endforeach;?>
        	</tbody>
        </table>
    <?php else:?>
    	<h3>No source found</h3>
    <?php endif;?>
</div>

</div>