<?php if(isset($this->result)) echo $this->result;?>
<form method="POST">
    New Status : <input type="text" name="message" value="" /><br/>
    <label for="post-to-fb">Post to Facebook: <input type="checkbox" name="post-to-fb" id="post-to-fb"/></label><br/>
    <label for="post-to-tw">Post to Twitter: <input type="checkbox" name="post-to-tw" id="post-to-tw"/></label><br/>
    <input type="submit" name="submit" />
</form>
