<?php
$lu = $this->row;
$step = get_value('_cl_step', '');
?>

	<ul class="nav nav-pills nav-stacked">
    		<li class=' <?php if ($step == 'account' || $step == '' ) echo 'active';?>'>
    		<a href="/user/update?id=<?php echo $lu['id'];?>&_cl_step=account">
    			<?php echo gen_icon('edit');?> <?php echo t("account",1);?></a></li>
    		<li class=' <?php if ($step == 'avatar') echo 'active';?>'>
    			<a href="/user/update?id=<?php echo $lu['id'];?>&_cl_step=avatar">
    			<?php echo gen_icon('picture');?> <?php echo t('avatar',1);?></a></li>
    		<li class=' <?php if ($step == 'change_pass') echo 'active';?>'>
    			<a href="/user/update?id=<?php echo $lu['id'];?>&_cl_step=change_pass">
    			<?php echo gen_icon('password');?> <?php echo t('change_password',1);?></a></li>
    		<li class=' <?php if ($step == 'crawler_apikey') echo 'active';?>'>
    			<a href="/user/update?id=<?php echo $lu['id'];?>&_cl_step=crawler_apikey">
    			<?php echo gen_icon('key');?> <?php echo t('crawler_api_key',1);?></a></li>
    		<?php if ($lu['status'] == 'unactivated') :?>
    		<li><a  href="/user/activate?id=<?php echo $lu['id'];?>"><?php echo t("active_account",1);?></a></li>
    		<?php endif;?>
    	</ul>
