				<h3><?php echo t("login_%s_with_only_1_click",1, DOMAIN);?></h3>
		        	<a href="/user/oauth?login=google"><i style='color:#B43222;' class='<?php echo get_icon('google-plus-sign');?>'></i> Google</a>
		        	&nbsp; &nbsp;&nbsp;
	        		<a href="/user/oauth?login=facebook"><i style='color:#5376B0;' class='<?php echo get_icon('facebook-sign');?>'></i> Facebook</a>
	        		&nbsp;&nbsp;&nbsp;
	        		<a href="/user/oauth?login=twitter"><i style='color:#00ABF0;' class='<?php echo get_icon('twitter');?>'></i> Twitter</a>
	        		&nbsp;&nbsp;&nbsp; 
	        		<a href="/user/oauth?login=yahoo"><img src='<?php echo SAND_ASSETS_CDN?>/images/yahoo-icon.png'/> Yahoo</a>
	        	<div class="clearfix clear" style="margin: 5px; 0"><?php echo t("you_will_automatically_get_an_account_after_signing_in_with_one_of_the_above_websites",1);?></div>
