<h1>Suspended Account</h1>
<p>
At StuffOwners.com, we try our best to fight against spams. Our spam fighter has detected that there are some strange recent activities with your account and consequently <b>blocked</b> your account.
</p>

<p>
This means that you can still login and <a href='/'>view the site's content </a> but you cannot do anything else. 
</p>
<p>
If you think this is an error send an email to <?php echo CONTACT_EMAIL;?>, we will address the issue appropriately. We apologize for any inconvenience caused by this.
</p>

