<?php 
	$viewUser = Zend_Registry::get('viewuser');
	$this->user= $viewUser;
?>
<script type="text/javascript">
CL.viewuser = "<?php echo $viewUser['id'];?>";
</script>
<div class="row user-info">
	<!--  
	<div class="col-md-8">
		<img alt="Cover img" src="http://placehold.it/500x300" width="100%"/>
	</div>
	-->
	<div class="col-md-4">
		<h1> <?php echo $this->user['name'];?></h1>
		<p> <?php echo t("number_of_post",1);?>: <?php echo $viewUser['counter']['p'];?></p>
	</div>
</div> <!--  end header row -->

<div class='row'>
	<!-- Begin tabber funny img and funny story -->
	<ul class="nav nav-tabs" id="myTab">
		<li class="active"><a data-toggle="tab" href="#post"><?php echo t("posted",1);?></a></li>
		<li class=""><a data-toggle="tab" href="#message"><?php echo t("private_messenger",1);?></a>
		</li>
	
	</ul>
	<div class="tab-content tab-ext" id="myTabContent">
		<div id="post" class="tab-pane fade active in">
			<?php 
				echo $this->render('widget/story-list.phtml');
			?>
		</div>
		<div id="message" class="tab-pane fade">
			<p><?php echo t("contact_with ");?> <?php echo $this->user['name'];?></p>
			<?php echo $this->render('/fun/face_comment.phtml');?>
		</div>
	
	</div>  
</div>