<script>
	var CL = {
        metadata : {}, callbacks : {}            
    };
    CL.GUEST_ID = <?php echo GUEST_ID;?>;
    CL.SAND_ASSETS_CDN = "<?php echo SAND_ASSETS_CDN;?>";
    CL.ASSETS_CDN = "<?php echo ASSETS_CDN;?>";
    CL.CODENAME = "<?php echo CODENAME;?>";
    CL.COOKIE_PREFIX = "<?php echo COOKIE_PREFIX;?>";
    CL.DOMAIN = "<?php echo DOMAIN;?>";
    CL.DEFAULT_AVATAR = "<?php echo DEFAULT_AVATAR_URL;?>";
	CL.page = "<?php echo Zend_Registry::get('page');?>"; 
	CL.APPLICATION_ENV = "<?php echo APPLICATION_ENV;?>";

    var modal_selector = '#ajaxModal'; //the jquery selector for the modal that will be opened upon clicking a.modal_ajax
    <?php $editorMode = Zend_Registry::isRegistered('editorMode') ? Zend_Registry::get('editorMode') : 'student';?>  
    CL.editorMode = '<?echo $editorMode;?>';

</script>