<?php echo sand_dev_info_phtml(__FILE__);?>

<div class='row'>
<div class='col-md-6'>
    <?php if (get_value('tags__slug')):?>
        <?php $tagSlug = get_value('tags__slug');
            $r = Dao_Node_Tag::getInstance()->findOne(array('slug' => $tagSlug));
            if($r['success'])
            {
                $tag = $r['result'];
            ?>
            <h3>Topic: <?php Echo $tag['name'];?></h3>
            <div class='well'>
            <?php echo $tag['content'];?>
            </div>
            <?php 
            }
        ?>
    <?php endif;?>
    <?php if($this->count > 0) :?>
    <div>
        <?php $page = get_value('page', 1);
            $perpage = get_value('items_per_page', 10);
        ?>
		<?php foreach($this->list as $i => $row) :?>
		    <?php $data = $row;?>
        	<div style='border-bottom:1px solid #eee;margin-top:10px;margin-bottom:30px;'>
    		    <h4><a href='<?php echo node_link('story', $row);?>' >
                    <?php if (isset($data['name'])):?>
                     <?php echo ($page - 1)* $perpage + $i + 1;?>. <?php echo $data['name'];?>
                    <?php endif;?>
                    </a> 
                    
                    <a href='javascript:void(0);' title='toggle item' style='float:right' 
                        class='toggle-dom' target-id='<?php echo $data['id'];?>'>+/-</a>
                </h4>
                
                <div id='<?php echo $data['id'];?>'>  
                    <div style='background-color:#F9F9F9;padding:5px;margin-bottom:10px;'>
                    <a href='<?php echo $data['ourl'];?>'><?php echo $data['sourceInfo']['name']?></a> / <b><?php echo $data['category_name']?></b> 
                    <span style='float:right;font-style:italic;'>  
                    <?php echo date('d/m/Y - h:i A', $row['ots']);?>
                    </span>
                    </div>
                      
                    <div>
            		<?php if (isset($data['avatar']) && $data['avatar'] != ''):?>
                    <img style='float:left; padding: 0px 10px 10px 2px;width:100px;' src='<?php echo $data['avatar'];?>'>
                    <?php endif;?>
                        
                        <?php if (isset($data['chapo'])):?>
                        <div class=''>
                            <?php echo $data['chapo'];?>.                     
                            <a href='javascript:void(0);' title='Click để đọc luôn'
                        class='toggle-dom' target-id='content-<?php echo $data['id'];?>'>Đọc</a>
                            
                        </div>
                        <?php endif;?>
                     </div>
                     <div style='clear:both;'></div>
                     <div style='padding-top:15px; display:none;' id='content-<?php echo $data['id'];?>'>   
                      <?php echo $data['content'];?>
                     </div>
                 </div>
    		</div>
		<?php endforeach;?>
    </div>
    <?php if($this->total > 0) :?>
        <?php echo $this->render("widget/pagination.phtml");?>
    <?php endif;?>
    
    <?php else:?>
    Oops! No news
    <?php endif;?>
</div>    
<div class='col-md-3'>
    <div class="panel panel-default" >
      <div class="panel-heading">
        <h3 class="panel-title">Top news</h3>
      </div>
      <div class="panel-body" >
          <?php echo $this->render('widget/hot-news.phtml');?>
      </div>
    </div>
</div>
<div class='col-md-3'>
     <div class="panel panel-default" >
      <div class="panel-heading">
        <h3 class="panel-title">Search</h3>
      </div>
      <div class="panel-body" >
        <?php echo $this->form;?>
      </div>
    </div>

</div>
</div>
<?php //v($this->list);?>
<?php $this->inlineScript()->captureStart();?>
$(document).ready(function(){
    hide_zf_element('service');
    hide_zf_element('pattern');
    hide_zf_element('type');
});
<?php $this->inlineScript()->captureEnd();?>
