<a href="/<?php echo $this->module?>/bulk-delete" class="cl_ajax btn btn-sm" 
	data-sand-callbacks-metadata="delete_bulk" 
>Delete all</a>
<div class="clear"></div>
<br/>
<table class="table table-striped table-bordered table-condensed">
	<thead>
		<tr>
			<th><input type="checkbox" class="checkall"/></th>
			<?php foreach($this->tableHead as $h) :?>
				<th><?php echo $h;?></th>
			<?php endforeach;?>
		</tr>
	</thead>
	<tbody>
		<?php foreach($this->list as $row) :?>
		<tr id="<?php echo $row['id'];?>">
			<td><input type="checkbox" value="<?php echo $row['id'];?>" class="check-item" /></td>
			<?php foreach($this->tableHead as $h) :?>
					<?php if(isset($row[$h])) :?>
						<?php if($h == 'id'):?>
							<td><?php echo Cl_Utility::charBreadcumb($row[$h], 8);?>...</td>
							<?php elseif($h == 'name'):?>
							<td><a href="/<?php echo $this->module;?>/<?php echo $row['id'];?>"><?php echo $row['name'];?></a></td>
							<?php else:?>
							<td><?php echo $row[$h];?></td>
							<?php endif;?>
						<?php endif;?>
						<?php if($h == 'action') :?>
						<td>
							<a href="/<?php echo $this->module;?>/update?id=<?php echo $row['id']?>" class="btn btn-sm"><i class="icon-edit"></i>Edit</a>
							<a href="/<?php echo $this->module;?>/delete?id=<?php echo $row['id']?>" 
								class="btn btn-sm cl_ajax" data-sand-ajax-confirm="yes" data-sand-callbacks-metadata="remove_my_parent:2">
								<i class="icon-remove"></i>Delete
							</a>
							<?php if(isset($row['extraActions'])) :?>
								<?php echo $row['extraActions'];?>
							<?php endif;?>
						</td>
					<?php endif;?>
				<?php endforeach;?>
		</tr>
		<?php endforeach;?>
	</tbody>
</table>