<?php 
$step = get_value('_cl_step', '');
$row = $this->row;
?>
<?php //This has to be there because jjcrop doesn't work with sizes properly
?>
<div class='row'>
<div class='col-md-12' style='padding-bottom:15px;margin-bottom:15px;display:none;border-bottom:1px solid gray' id='re-upload-image' >
    <a  href='<?echo $_SERVER['REQUEST_URI'];?>' class='btn btn-primary'>
    <?php echo gen_icon('upload');?> <?php echo t('reupload_new_image', 1);?></a>
</div>
</div>

<div class='row'>

<div class='col-md-4'>
    <div id='crop_div_wrapper' style='display:none;' >
         <a id='use-cropped-avatar' class='btn btn-xs btn-primary' href='#'><?php echo gen_icon('ok');?> 
         <?php echo t('use_this_cropped_avatar',1 );?></a>
        <br/><b><?php echo t('newly_cropped_avatar', 1);?></b><br/>
        <div style='text-align:center;' >
        <img width="100%" height="100%" src='' id='cropped_avatar' class='img-thumbnail'/>
        </div>
    </div>

    <div id='current-avatar-wrapper'>
        <h5><b><?php echo t('current_avatar', 1);?></b> <a id='edit-current-avatar'
            href='#' title='Edit current avatar'><?php echo gen_icon('edit');?></a></h5>
        <div style='overflow:hidden;text-align:center;'>
        <?php 
            $ava = isset($row['avatar']) ? $row['avatar'] : DEFAULT_AVATAR_URL;
        ?>
        <a href='<?php echo $ava;?>' target='_blank'>
            <img data-oavatar='<?php if (isset($row['oavatar'])) echo $row['oavatar']; elseif (isset($row['avatar'])) echo $row['avatar'];?>'
                src='<?php echo $ava;?>' width='100%;' class='img-thumbnail' id='old-avatar'/></a>
        </div>
    </div>
</div>

<div class='col-md-8'>
    <div id='avatar_actions' style='display:none;'>
        <div style='margin-bottom:15px;'>
            <?php
            /* 
         <a id='start_jcrop' class='btn btn-xs' href='#'><?php echo gen_icon('edit');?> Edit (crop) this image</a> or
         */
            ?>
         <a id='crop_avatar' class='btn btn-default btn-xs has-tooltip' href='javascript:void(0);' 
         title='<?php echo t('crop_image_drag_drop_help',1);?>'
         > 
        <?php echo gen_icon('cut');?> <?php echo gen_icon('ok')?> <?php echo t('crop_image');?></a>
        <?php
        /* 
         <a id='use_original_image' class='btn btn-xs btn-default' href='#'><?php echo gen_icon('ok');?> 
         <?php echo t('use_uploaded_avatar',1);?></a>
         */
        ?>
         <br/>
        </div>
    </div>
    <div>
    <img id='uploaded_avatar' src='' width="500px;"/>
    </div>
</div>

</div>

<div class='row'>
    <div class='col-md-12'>
            <div class='alert alert-info' id='help_on_crop'  style='margin-top:30px; margin-bottom: 10px;'>
        <ul>
        <li>Click on the image & drag to select an area</li>
        <li>If you're happy with the image. Click "Crop Image" button. </li>
        <li>A new cropped avatar will be presented to you. If you're happy with it. Click "Use cropped avatar"</li>
        </ul>
        </div>
    
    
    </div>
</div>


<?php $jcropDir = SAND_ASSETS_CDN . '/js/plugins/jcrop/0.9.12';?>
<link rel="stylesheet/less" type="text/css" href="<?php echo $jcropDir. '/css/jquery.Jcrop.css';?>">
<?php $this->headScript()->appendFile($jcropDir . '/js/jquery.Jcrop.js');?>



<style>
#old-avatar {max-width: none}
 .jcrop img {max-width: none}
 img {max-width: none}
</style>
<?php $this->inlineScript()->captureStart();?>
$(document).ready(function(){
    $("#_cl_submit").hide();
});
<?php $this->inlineScript()->captureEnd();?>