<?php echo sand_dev_info_phtml(__FILE__);?>
<?php $tmp = explode(':', $row['slug']);
      $pos = $tmp[count($tmp)-1];
      if($pos == 'top1'):
         $span = 'col-md-9';
      if($pos == 'top2')
          $span = 'col-md-3';
      if($pos == 'left')
          $span = 'col-md-6';
      if($pos == 'right')
          $span = 'col-md-6';
?>
<style>
<!--
#launchPad {
    float:left;
    border: 1px solid #eaeaea;
    background-color: #f5f5f5;
}
#dropZone {
    float:right;
    border: 1px solid #eaeaea;
    background-color: #ffffcc;
}
.card { 
    padding: 5px 10px;
    margin:5px;
    border:1px solid #ccc;
    background-color: #eaeaea;
}
.stack {
    border: 1px solid #ccc;
    background-color: #f5f5f5;
}
.stackHdr {
    background-color: #eaeaea;
    border-bottom: 1px solid #fff;
}
.stackDrop{
    min-height:100px;
    padding: 15px;
}

-->
</style>
<div class="row">
<div class="col-md-12">
<!-- Drop zone, Allow .card -->
<div id="dropZone" class="col-md-9">
<div class="row">
    <div class="stack col-md-9">
        <div class="stackHdr row">
            Top1
        </div>
        <div class="stackDrop row">
            
        </div>
    </div>
    <div class="stack col-md-3">
        <div class="stackHdr row">
            Top 2 
        </div>
        <div class="stackDrop row">
            
        </div>
    </div>
    </div>
    <div class="row">
    <div class="stack col-md-6">
        <div class="stackHdr row">
            Left
        </div>
        <div class="stackDrop">
            
        </div>
    </div>
    <div class="stack col-md-6">
        <div class="stackHdr row">
            right
        </div>
        <div class="stackDrop">
            
        </div>
    </div>
    </div>
</div>

<!-- story list -->
<div id="launchPad" class="col-md-3">    
    <div class="card">
        apple
    </div> 
    <div class="card">
        orange
    </div> 
    <div class="card">
        banana
    </div> 
    <div class="card">
        car
    </div> 
    <div class="card">
        bus
    </div> 
</div>
<!-- end of story list -->
</div>
<!-- Drop zone, Allow .card -->
</div>
<?php 
$this->headScript()->headScript()->prependFile(SAND_ASSETS_CDN . "/js/jquery-ui/jquery-ui-1.10.3.custom/js/jquery-ui-1.10.3.custom.min.js");
$this->headScript()->headScript()->prependFile(SAND_ASSETS_CDN . "/js/3rdparty/jquery.simulate.drag-sortable.js");
$this->headScript()->headScript()->prependFile(ASSETS_CDN . "/js/dragndrop.js");
$this->headLink()->appendStylesheet(SAND_ASSETS_CDN . "/js/jquery-ui/jquery-ui-1.10.3.custom/css/ui-lightness/jquery-ui-1.10.3.custom.css");
?>
<?php $this->inlineScript()->captureStart();?>

$("#launchPad").height($(window).height() - 20);


/*
var dropSpace = $(window).width() - $("#launchPad").width();
$("#dropZone").width(dropSpace - 70);
$("#dropZone").height($("#launchPad").height());
*/

$(".card").draggable({
    appendTo: "body",
    cursor: "move",
    helper: 'clone',
    revert: "invalid"
});

$("#launchPad").droppable({
    tolerance: "intersect",
    accept: ".card",
    activeClass: "ui-state-default",
    hoverClass: "ui-state-hover",
    drop: function(event, ui) {
        $("#launchPad").append($(ui.draggable));
    }
});

$(".stackDrop").droppable({
    tolerance: "intersect",
    accept: ".card",
    activeClass: "ui-state-default",
    hoverClass: "ui-state-hover",
    drop: function(event, ui) {        
        $(this).append($(ui.draggable));
    }
});
<!--

//-->

<?php $this->inlineScript()->captureEnd();?>