<?php echo sand_dev_info_phtml(__FILE__);?>

<div class=''>
<?php $page = Zend_Registry::get('page');?>
<ul class='nav nav-pills nav-stacked'>
	<li <?php if ($page == 'list/index/new') echo "class='active';"?>>
		<a title='Add new' href="/list/new?type=1"><?php echo gen_icon('plus');?> <?php if (!isset($this->compactMode)):?>New<?php endif;?></a></li>
	<? if (isset($this->row)) :?>    
	<li><a title='Preview' href='<?php echo node_link('list', $this->row);?>'><?php echo gen_icon('preview');?> 
	<?php if (!isset($this->compactMode)):?>View<?php endif;?></a></li>
	<li <?php if ($page == 'list/index/update' && $this->step == '') echo "class='active';"?>>
		<a title='Update' href="/list/update<?php if (isset($this->row['id'])) echo "?id=" . $this->row['id'];?>">
		<?php echo gen_icon('wrench');?> <?php if (!isset($this->compactMode)):?>Update<?php Endif;?></a></li>
	<li <?php if ($page == 'list/index/update' && $this->step == 'list_items_order') echo "class='active';"?>>
		<a title='Order items' href="/list/update<?php if (isset($this->row['id'])) echo "?id=" . $this->row['id'];?>&_cl_step=list_items_order">
		<?php echo gen_icon('list');?> <?php if (!isset($this->compactMode)):?>Items<?php Endif;?></a></li>
		
	<?php endif;?>    
	<li title='Search widgets' <?php if ($page == 'list/index/search') echo "class='active';"?>><a href="/list/search">
		<?php echo gen_icon('search');?> <?php if (!isset($this->compactMode)):?>Search<?php endif;?></a></li>
</ul>

<div style='min-height:10px;'></div>
</div>