<?php echo sand_dev_info_phtml(__FILE__);?>
<?php echo $this->render('index/top-nav.phtml');?>

<div class='row' >

<?php $page = Zend_Registry::get('page');?>
<div class='col-md-2'>
<?php echo $this->render('index/navbar.phtml');?>
</div>
<div class='col-md-6'>
<?php if ($page == 'list/index/new'):?>
<h1 class='margin-top-0'> <?php echo t('new_list',1);?></h1>
<?php endif;?>
<?php $this->form->setAttrib('class', 'cl_ajax');?>
<?php echo $this->form;?>
</div>
<div class='col-md-4'>
    <div id='help-area' class='alert alert-info'>
    <pre>
List là 1 phần logic để quản lý danh sách các item với nhau ...Dùng để hiển thị ra ngoài .
Tên không quan trọng
Slug có dạng giao-duc:category:top1 hoặc home:top2...
1 số líst sẽ đc sinh tự động khi update template (tick vào phần generate list tự động)
    </pre>
    </div>
</div>
</div>