<?php echo sand_dev_info_phtml(__FILE__);?>

<?php echo $this->render('index/top-nav.phtml');?>

<div class='row' >
<div class='col-md-1'>
<?php $this->compactMode = 1;?>
<?php echo $this->render('index/navbar.phtml');?>
</div>

<div class='col-md-2'>
    <div class='search_form well form-fit-width well-shallow'>
    <?php $this->form->setDisplayInline();
        $this->form->setAttrib('id' , 'search_form');
    ?>
    <?php echo $this->form;?>
    </div>
</div>

<div class='col-md-9'>
	<div>
	nên có home:top1, giao-duc:category:top1, xa-hoi:category:top2
	
	</div>
    <?php if($this->total > 0) :?>
        <?php echo $this->render("widget/pagination.phtml");?>
    <?php endif;?>
    
    <?php if($this->count > 0) :?>
	
    	<?php //echo $this->render('widget/table.phtml');?>
    	<a href="/list/bulk-delete" id='bulk-delete' class="cl_ajax btn btn-xs btn-danger"><i class='icon-remove'></i> Delete Selected</a>
    	<div class="clear"></div>
    	<br/>
        <table class="table table-striped table-bordered table-condensed">
        	<thead>
        		<tr>
        			<th><input type="checkbox" class="checkall"/></th>
        			<?php
        			/* 
        			<th>ava</th>
        			*/
        			?>
        			<th>Id (slug)</th>
        			<th>Name</th>
        			<th>Prefich</th>
        			<th>Limit</th>
        			<th>Items</th>
        			<th style='width:15%;'>Status</th>
        			<th style='width:5%;'>Action</th>
        		</tr>
        	</thead>
        	<tbody>
        		<?php foreach($this->list as $row) :?>
        		<?php 
        		if (!isset($row['avatar']) || $row['avatar'] == '')
        			$row['avatar'] = ASSETS_CDN . '/images/avatar.gif' ;
        		?>
        		<tr id="<?php echo $row['id'];?>">
        			<td><input type="checkbox" value="<?php echo $row['id'];?>" class="check-item" /></td>
        			<?php
        			/* 
        			<td>
        			<?php if (isset($row['avatar'])):?>
        			<a href="<?php echo node_link('list',$row);?>">
        			<img class='img50 thumbnail' src='<?php echo $row['avatar'];?>'/></a>
        			<?php endif;?>
        			</td>
        			*/
        			?>
        			
        			<td>
        			<?php echo $row['slug'];?>
        			</td>
        			
        			
        			<td><a title="type : <?php echo $row['items_type'];?>" class='modal_ajax preview_story' href="<?php echo node_link('list',$row);?>">
    					<?php echo gen_icon($row['items_type']);?>    			
	        			<?php echo $row['name'];?></a>
        			</td>
        			<td>    			
	        			<?php echo $row['prefich'];?>
        			</td>
        			<td>
        			<?php if (isset($row['lim'])):?>
        				<?php echo $row['lim'];?>
        			<?php endif;?>
        			</td>
					<td>
					<?php if (count($row['items_order']) > 0):?>
					<?php foreach ($row['items'] as $idx => $i):?>
						<?php //v($i);?>
						<?php echo ($idx + 1);?>. <?php echo node_anchor($i['type'], $i);?> <br/>
					<?php endforeach;?>
					<?php endif;?>
					<a class='pull-right' href='/list/update?id=<?php echo $row['id'];?>&_cl_step=list_items_order'>
						<?php echo gen_icon('list');?> Order</a>
					</td>        			

        			<td>
                        <div class="btn-group">
        			    	<a href="/list/update?id=<?php echo $row['id'];?>&status=0&_cl_step=status"
        			    	class="btn btn-primary btn-xs <?php if($row['status']==0) echo 'active';?> cl_ajax" 
        			    	data-sand-callbacks-metadata="active_button_group">Q.</a>
        			    	<a href="/list/update?id=<?php echo $row['id'];?>&status=1&_cl_step=status"
        			    	class="btn btn-primary btn-xs <?php if($row['status']==1) echo 'active';?> cl_ajax" data-sand-callbacks-metadata="active_button_group">Apprvd</a>
        			    </div>
        			</td>
        			
        			<td>
        				<a href="/list/update?id=<?php echo $row['id']?>" class="btn btn-default btn-xs"><i class="icon-edit"></i> Edit</a>
        				<a href="/list/delete?id=<?php echo $row['id']?>" 
        					class="btn btn-xs btn-danger cl_ajax" data-sand-callbacks-metadata="remove_my_parent:2"
        					data-sand-ajax-confirm='Are you sure you want to permanently delete this item?'
        					>
        					<i class="icon-remove"></i> Delete
        				</a>
        			</td>
        		</tr>
        		<?php endforeach;?>
        	</tbody>
        </table>
    <?php else:?>
    	<h3>No list found</h3>
    <?php endif;?>
</div>

</div>