<?php echo sand_dev_info_phtml(__FILE__);?>


<?php if ($this->step == 'list_items_order'):?>
<?php echo $this->render('index/top-nav.phtml');?>
<div class='row' >
<div class='col-md-1'>
<?php $this->compactMode = 1;?>
<?php echo $this->render('index/navbar.phtml');?>
</div>

<div class='col-md-11'>
<div class='row'>
	<div class='col-md-12'>
	    <?php echo $this->render('index/order-items.phtml');?>
	</div>
</div>
</div>
</div>
<?php else:?>
	<?php echo $this->render('index/new.phtml');?>
<?php endif;?>
