
<div class='row'>
<div class='col-md-12'>

<?php 
$lname = 'a@g.com';
$pass = '123';
$_app_id="6998c62207fe21515b9d0bcc259fc7a820a1a4bba879c01a622da400c233857c";
$url_ytb='https://www.youtube.com/watch?v=05C47EeF8rg';
$time=time();

$images = array(
	array('id' => 'test', 'ext' => 'jpg')
);
$uiid=$_COOKIE['_cl_uiid'];

$imagesJson = json_encode($images);
$_cl_uid="532c70b3afea0d7c0f002d12"; //id mongodb
$cl_uid=1004;				//user
$_cl_token="533454e3afea0dd412003a2d";
$code="AQCWIRT-DKQHf2YwGY8DldLJHi7yc4lNc6kWoc5l9Fbwnz7xZBc7TCEMZjBDmG8qLYyJEhens3pR6Tg-D2sKY3yabI2dJ2fMlzq_mG_eh11EZUFuJCRVXp8HQAGkPLFlc0w2ENXKMQ0s-m61epG6wVoHRsFIGbxy-x3BgbdP-5c2mezMuUxERlSYnNWOmu3_41naF6603FWdiKVZHi2QXIFipmw9nz5eH7OxyNE7i2bG-GfsGVDAZFGxaPGNPB9iDsPy9NefQWWvtBct59MDMbv3J8I6naTFEPdlCyrYEYrxPSyxhorh2nAWb0dgehZl7Pk";
$access_token="CAAAAGatyXfQBAGZB20xzZCCmRyJ4C8ccWHzsCNThBMwNgSdlZBaJ8GhqFbvsaXaNcPZC6UCz1TpPYvMYoFMCGNy63hvJ4v9P4tvWFuhtoIv94ZBbXkTXOb7rY6ZATamKUwekBwIsfSzi2GJq3BX9jA08Elhw5L9GUafsIEFZBzPj1oHZByyZCCxXzzoQMwQW5XmkZD";
$deviceID="android";
$u=Zend_Registry::get('user');
 $url_common="&_cl_rest=1&_cl_submit=1&_cl_ajax=1&_app_id=".$_app_id."&_cl_platform=1&_cl_ts=".$time. "&_cl_deviceID=". $deviceID;

 
 
 
 
$api = array(
	array(
			'link' => "/user/login?lname={$lname}&pass={$pass}&remember=1",
			'name'=>'Login',
			'support'=>"uiid=iid"
			
	),
	array(
			'link' => "/user/oauth?login=facebook",
			'name'=>'Login Facebook',
			'support'=>""
		
					),
	array(
		'link' => '/user/logout?',
		'name'=>'Logout',
		'support'=>''
	),
	
	array(
			'link'=>'/user/'.$uiid.'?',
			'name'=>'List Story',
			'support'=>'/user/<b>1004</b>
						<br> uiid=1004
						<br>Đây là danh sách nhũng story của một user đã post'
	),
	array(
			'link' => '/hot?'	,
			'name'=>'Hot Story',
			'support'=>''
	),
	array(
			'link' => '/hot/2?'	,
			'name'=>'Hot Story page 2',
			'support'=>'/story/hottags?'
	),
	array(
			'link' => '/story/new?type=1&name=truyenmoi&content=contenttruyen&_cl_step=story',
			'name'=>'New Story (type 1)',
			'support'=>'Tạo một story mới (<b>Chu y</b>: user dang nhap moi co the post bai moi)<br>
        		<b>return</b> (e.g):({"success":true,"result":{"id":"<b>5330c3abafea0dec0f006899</b>","slug":"truyen-moi-7","type":1,"iid":884},"callback":"redirect","data":{"url":"\/truyen-cuoi\/884-truyen-moi-7.html"}}) '
	),
	array(
			'link' => '/site/upanh?',
			'name'=>'Up file',
			'support'=>'Complete return:{"success":true,"result":{"attachments":[{"u":{"id":"5330c038afea0d6c15003459","name":"a@g","avatar":""},"id":"5330cf4aafea0d4414000588","ext":"jpg","name":"batung.jpg","link":"http:\/\/funstatic.local\/\/5330cf4aafea0d4414000588.jpg"}]}} '
	),
	array(
			'link' => "/story/new?type=2&name=anhmoi&content=abc&images={$imagesJson}",
			'name'=>'Post new story image',
			'support'=>'Create new story (type 2)<br>
	        	<b>id=5330c038afea0d6c15003459</b> lấy từ phần up ảnh "up file image"
	        	/story/new?type=2&name=anhmoi&content=abc&images=[{"id":"<b>5330c038afea0d6c15003459</b>","ext":"jpg"}]'
	),
	array(
			'link' =>'/user/relate?id=532a9d8d9ecf87d80f006e7e&object=story&rt=1&type=vote',
			'name'=>'Vote up',
			'support'=>'Vote +1 cho một story ( chú ý: login, user chưa vote sotry đó )<br>
        		Eg: lấy Id ở phần Post New: <b>id=5330c3abafea0dec0f006899</b><br>
        		/user/relate?id=5330c3abafea0dec0f006899&object=story&rt=1&type=vote
        		<br><b>return:</b> ({"success":true,"callback":"alert_success"}) ( Vote up thành công)'
	),
	array(
			'link' =>'/user/relate?id=532a9d8d9ecf87d80f006e7e&object=story&rt=4&type=vote',
			'name'=>'Vote Down',
			'support'=>'Vote -1 cho một story (chú ý đăng nhập, user đã vote story đó )<br>
        	E.g: lấy Id vừa vote thành công ở trên <b>id=5330c3abafea0dec0f006899</b><br>
        	/user/relate?id=5330c3abafea0dec0f006899&object=story&rt=4&type=vote
        	<b>return</b> ({"success":true,"callback":"alert_success"}) (vote down thanh cong)'
	),
	array(
			'link' =>'/story/hottags?',
			'name'=>'Hot Tags)',
			'support'=>''
	),
	array(
			'link'=>'/tagged/test?',
			'name'=>'Get storys from a tag',
			'support'=>'<b>test</b>: is name tag'
	),
	array(
			'link' =>'/story/new?type=3&name=name youtube&content= content youtube&_cl_step=video&ytid=05C47EeF8rg&url='.$url_ytb,
			'name'=>'Post new story youtube',
			'support'=>'Create new story yotube(type 3)<br>
	        	/story/new?type=3&name=name youtube&content=content youtube&_cl_step=video&ytid=05C47EeF8rg&url=https://www.youtube.com/watch?v=05C47EeF8rg
	           <br><b>url</b>=https://www.youtube.com/watch?v=<b>05C47EeF8rg</b>
	           <br><b>ytid</b>=05C47EeF8rg là id của youtube (là phần in đậm trên url)'
	),
	array(
			'link' =>'/user/forgot-password?mail=thoahv@chippoo.com',
			'name'=>'Reset password',
			'support'=>'/user/forgot-password?mail=<b>thoahv@chippoo.com</b>
	           <br><b>Email User </b>thoahv@chippoo.com</b> '
	),
	array(
			'link' =>'/user/register?name=AKia&pass=123&mail=d@a.com',
			'name'=>'Sign up',
			'support'=>'	/user/register?name=<b>AKia</b>&pass=<b>123123</b>&mail=<b>d@a.com</b>'
	),
array(
		'link'=>'/story/counter-new-story?',
		'name'=>"New notification",
		'support'=>''
		
),
	array(
			'link'=>'/user/oauth-mobile-token-success?login=facebook&access_token='.$access_token,
			'name'=>'Login Facebook request access token',
			'support'=>''
	),
	array(
			'link'=>'/hot?type[]=2',
			'name'=>'Hot Image',
			'support'=>'Parameter: type[]=1&type[]=2&..
						<br>type=>(<b>1=> jokes</b>,<b>2 => pics</b>,<b>3 => videos</b>,<b>4 => quiz</b>)'
	),
	array(
			'link'=>'/new?type[]=2&type[]=1',
			'name'=>'New Image',
			'support'=>'
						type=>(<b>1=> jokes</b>,<b>2 => pics</b>,<b>3 => videos</b>,<b>4 => quiz</b>)'
	),
	array(
			'link'=>'/best?type[]=2',
			'name'=>'Best Image',
			'support'=>'type=>(<b>1=> jokes</b>,<b>2 => pics</b>,<b>3 => videos</b>,<b>4 => quiz</b>'
	),
	array(
			'link'=>'/vote?type[]=1&type[]=3',
			'name'=>'Vote',
			'support'=>'type=>(<b>1=> jokes</b>,<b>2 => pics</b>,<b>3 => videos</b>,<b>4 => quiz</b>'
	),
	array(
			'link'=>'/story/new-fb-like?id=5349a56fafea0dc8130063cb&rt=1&uiid='.$u['iid'],
			'name'=>'Check like fb',
			'support'=>'After click button like fb callback
						<br><b>id</b> is id of story, <b>uiid</b> is id user,<b>rt=1</b> default<br>
						<b>Note:</b> User already login'
	),
	array(
			'link'=>'/site/good-app?',
			'name'=>'Good App',
			'support'=>'get good apps',	

)
);

?>
<h1>List of Apis</h1>
<div>
<!-- _api_id sha key: waymobi@2014 -->
For mobile devices or jquery mobile app, always send the following params
<pre>
 - _cl_rest=1
 - _cl_ajax=1
 - _cl_submit=1
 - _cl_uid=$mongoId
 - _cl_uhash=$has user (returned when logging in)
 - _cl_token=$token (returned when logging in)
 - _app_id (SHA:6998c62207fe21515b9d0bcc259fc7a820a1a4bba879c01a622da400c233857c) (static)
 - _cl_platform : 1 = android, 2 = ios
 - _cl_deviceID
 - <span style="color:red">_cl_ts</span> (la thoi gian hien tai)
</pre>
</div>


</div>
</div>
<h2>Giải thích</h2>
<pre>
		<ul>- Tất cả các đường link đều được cộng thêm: 
			<li><span style="color:blue">&_cl_rest=1&_cl_submit=1&_cl_ajax=1&_app_id=6998c62207fe21515b9d0bcc259fc7a820a1a4bba879c01a622da400c233857c&_cl_platform=1&_cl_ts=<?php echo time()?></span></li>
			<li> _cl_ts là thời gian hiện tại: cl_ts=<?php echo $time;?></li>
		</ul>
</pre>






<br>
<div class="table-responsive">
    <table class="table table-bordered table-striped">
      <tbody>
      <?php 
      foreach($api as $row)
      {
      	echo "<tr>";
      		echo "<td><a target='_blank' href='".$row['link'].$url_common."'>".$row["name"]."</a></td>";
			echo "<td>".$row['support']."</td>";
      	echo "</tr>";
      }
      
      ?>
      
      </tbody>
   </table>
</div>

	<h2 style="color:red">Note:</h2><br>
	<pre>
	<ol>
		<li><h3>Post new story youtbe, Reset Password , Sign up(<b>Update</b>26/3/2014)</h3></li>
		<li><h3>Chuyển _cl_Platform thành cl_platform</h3></li>
	
	</ol>
</pre>


