<?php 
	$allowedCates = array('thong-bao', 'tin');
	foreach ($allowedCates as $cateSlug):?>
	<?php $r = Dao_Node_Category::getInstance()->findOne(array('slug' => $cateSlug));
		if ($r['success'])
			$cate = $r['result'];
	?>
	<div class="panel panel-default">
	      <div class="panel-heading">
	        <h3 class="panel-title"><a href='/?category=<?php echo $cateSlug;?>'><?php echo $cate['name']?></a></h3>
	      </div>
	      <div class="panel-body">
	        	<?php 
	        	$cond = array('where' => array('category' => $cateSlug),
					'limit' => 10,
					'order' => array('weight' => -1)
				);
	        	$r = Dao_Node_Story::getInstance()->find($cond);
	        	if ($r['success'] && count($r['result']) > 0)
	        	{
	        		$data = $r['result'][0];
        		?>
        		<h4><a href='<?php echo node_link('story', $data);?>' >
                     <?php echo $data['name'];?>
                    </a> 
                    
                    <a href='javascript:void(0);' title='toggle item' style='float:right' 
                        class='toggle-dom' target-id='<?php echo $data['id'];?>'>+/-</a>
                </h4>
	      		<div>
            		<?php if (isset($data['avatar']) && $data['avatar'] != ''):?>
                    <img style='float:left; padding: 0px 10px 10px 2px;width:100px;' src='<?php echo $data['avatar'];?>'>
                    <?php endif;?>
                        <?php if (isset($data['chapo'])):?>
                        <div class=''>
                            <?php echo $data['chapo'];?>.                     
                            <a href='<?php echo node_link('story', $data);?>' title='Click để đọc luôn'
                        	>Đọc</a>
                        </div>
                        <?php endif;?>
                        
	      		</div>
		        <ul style='padding-left:5px;'>
		        		<?php foreach($r['result'] as $i => $item):?>
		        			<?php if ($i >= 1):?>
		            		<li><a target='_blank' href="<?php echo $item['ourl']?>"><?php echo $item['name'];?></a></li>
		            		<?php endif;?>
		        		<?php endforeach;?>
		        		<?php 
		        	}
		        	?>
		        </ul>
	      </div>
	</div>	
	
<?php endforeach;?>	