<div class='row'>
<div class='col-md-2' style='padding-left:0px;'>
	<?php echo $this->render('laichau/left-menu.phtml');?>
</div>
<div class='col-md-8' style='padding-left:0px;'>
	<?php
	$cateSlug = get_value('category');
	$cateWhere = array('slug' => $cateSlug);
	$t = Dao_Node_Category::getInstance()->findOne($cateWhere);
	if ($t['success'])
		$category = $t['result'];
	  
	$dao = Dao_Node_Story::getInstance();
	$where = array('category' => $cateSlug);
	$r = $dao->findAll(array('where' => $where));
	if ($r['success'])
	{ 
		$links = $r['result'];
	}
?>
<h3><?php echo $category['name'];?></h3>
<?php foreach ($links as $c):?>

<div style='margin-bottom:5px;clear:both;'>
	<i style='font-size:70%;' class='<?php echo get_icon('chevron-right');?>'></i> 
	<a href='<?php echo node_link('story', $c);?>'>
		<?php echo $c['name']?>
	</a>	
	(<?php echo date('d/m/Y', $c['ts']);?>)
	<div>
	<img src='<?php echo $c['avatar'];?>' class='img-resposive img-rounded' style='width:140px;float:left'/>
	<p style='float:left;padding-left:30px;'>
		<?php echo $c['chapo'];?>
	</p>
	</div>
</div>

<?php endforeach;?>

</div>


<div class='col-md-2' style='padding-left:0px;'>
	<?php echo $this->render('laichau/right-menu.phtml');?>
</div>
</div>
