<style>
strong {
	color: #0088CC;
}
</style>
	<a name="features"></a>
	<!-- Sign up -->
	<div class='row well'>
		<div class="span6 offset3">
			<a href="/user/oauth?login=yahoo" class="btn btn-sm">
				<i class = "icon-sm-yahoo"></i>SignIn with Yahoo
			</a>
			<a href="/user/oauth?login=google" class="btn btn-sm">
				<i class = "icon-sm-google"></i>SignIn with Google
			</a>
			<a href="/user/oauth?login=twitter" class="btn btn-sm btn-info" style="font-weight:bold;">
				<i class = "icon-sm-twitter"></i>SignIn with Twitter
			</a>
			<a href="/user/oauth?login=facebook" class="btn btn-sm">
				<i class = "icon-sm-facebook"></i>SignIn with Facebook
			</a>
		</div>
        <div class='span3 offset3' id='register_form'>
        	<a name="signup"></a>
        	
        	<h3>Sign up</h3>
        		It's free!
        	<?php 
        	    $form = new User_Form_Register();
                $form->build();
                $form->setAction('/user/register')
                    ->setAttrib('class', 'cl_ajax');
                echo $form;
        	?>
        </div>
        <div class='span3'>
        	<div id='login_form'>
        	<h3>Login</h3>
        	Forgot your password? <a href="/user/forgot-password" id='remind_password'>Receive a new one</a>
        	<?php 
        	    $form = new User_Form_Login();
                $form->build();
                $form->setAction('/user/login')
                    ->setAttrib('class', 'cl_ajax');
                echo $form;
        	?>
        	</div>
        	
        	<div id='remind_password_form' style='display:none'>
    		<h3>Remind password</h3>
        	<b style='color:green'><a href='/user/login' id='login'>Login</a></b>
        	<?php 
        	    $form = new User_Form_RemindPassword();
                $form->build();
                $form->setAction('/user/forgot-password')
                    ->setAttrib('class', 'cl_ajax');
                echo $form;
        	?>        	
        	
        	</div>
        </div>
		        
	</div>
	
	<div class='row'>
		<div class='span12'>
		<h3>Download mobile apps</h3>
		</div>
	</div>
	
	<div class='row'>
	<hr/>
	<div class='span3'>
    	<h3>iPhone</h3>
    	<div>
    		<p>
    		Iphone
    		</p>
    	</div>
	</div>
	
	<div class='span3'>
    	<h3>Android</h3>
    	<div>
    		<p>
    		Android
    		</p>
    	</div>
	</div>

	<div class='span3'>
    	<h3>Windows</h3>
    	<div>
    		<p>
    		Windows
    		</p>
    	</div>
	</div>

	<div class='span3'>
    	<h3>BlackBerry</h3>
    	<div>
    		<p>
    		BlackBerry
    		</p>
    	</div>
	</div>
	
	</div>	
<?php $this->inlineScript()->captureStart();?>
$(document).ready(function(){
    $("#login").click(function(e){
    	e.preventDefault();
    	$("#login_form").show();
    	$("#remind_password_form").hide();
    });
   
    $("#remind_password").click(function(e){
    	e.preventDefault();
    	$("#login_form").hide();
    	$("#remind_password_form").show();
    });
});
<?php $this->inlineScript()->captureEnd();?>
