Dear <?php echo $this->to;?>, <br/>
<p>
Thank you for registering on Stuffowners.com. To use all of our features, you need to verify your email address. </p>
<p>Please click the following link to verify <a href='<?php echo SITE_URL?>/user/verify-email?token=<?php echo $this->params['token']?>&uid=<?php echo $this->params['id']?>'><?php echo SITE_URL?>/user/verify-email?token=<?php echo $this->params['token']?>&uid=<?php echo $this->params['id']?></a><br/>
</p>
<?php echo $this->render('/templates/notif/email-footer.phtml');?> 