Dear <?php echo $this->to;?>, <br/>
<p>
At StuffOwners.com, we try our best to fight against spams. Our spam fighter has detected that there are some strange recent activities with your account and consequently <b>blocked</b> your account.
</p>

<p>
This means that you can still login and view the site's content but you cannot do anything else. 
</p>
<p>
If you think this is an error simply reply to this email, we will address the issue appropriately. We apologize for any inconvenience caused by this.
</p>

<br/>
<p>Thank you </p>
<p>StuffOwners.com team </p>

<?php //echo $this->render('/templates/notif/email-footer.phtml');?> 