<?php echo sand_dev_info_phtml(__FILE__);?>
<?php 
$theme = Zend_Registry::get('theme');
$templateName = get_value('template');
$span1 = 8;
$span2 = 2;
$span3 = 12 - $span1 - $span2;

$formClass = "Story_Form_Search";
$attr = array(
        'method' => "POST",
        'action' => '/story/search'
);
//Set step
$form = new $formClass();
//if (null !== $step)
$form->setStep('list_items_order');
$form->attributes = $attr;
$form->build($_REQUEST);
$this->form = $form;
$form->setAttrib('class', 'cl_ajax');
$form->setAttrib('id', 'search-form2');
$form->setAttrib('data-sand-callbacks', 'list-items-order-search-items');

?>
<?php //echo $this->render('index/top-nav.phtml');?>
<div class='row' >

<div class='col-md-<?php echo $span1;?>'>
<?
    $this->renderMode = 'admin';
    $path = "index/$theme/{$templateName}.phtml";
 	 echo $this->render($path);
?>
</div>


<div class="col-md-<?echo $span2;?>">
	<div class='card'>
		Drag and Drop items from this column to template
	</div>
	
	<div id='search-results'>
	
	</div>
	
	<div>
		<ul class='pagination' id='search-results-pagination' data-target-form-selector='#search-form2'>
			<li class='active'><a href='#'>1</a></li>
			<li><a href='#'>Next</a></li>
		</ul>
   	
    	<textarea id='search-result-pagination-tpl' style='display:none;'>
    	{{#list}}
    		<li class="{{active}}">
    			<a data-page={{page}} href='javascript:void(0);'>{{page_display}}</a>
    		</li>
    	{{/list}}
    	</textarea>		
	</div>
	
</div>
<div class="col-md-<?php echo $span3;?>">
	<div>
    <h4>Filter Story</h4>
    </div>
    <div>
    	<div class='card'>
    	<?php echo $form;?>
    	</div>
    	
    	
    	<textarea id='search-result-item-tpl' style='display:none;'>
    	<div class="connectedSortable">
    	{{#result}}
    		<div class='item-bank {{item-exists}} card'
    			title="click to preview news" 
    			data-item-id='{{id}}'>
    			<a href='{{link}}' class='preview modal_ajax'>
    			<span>{{name}}</span>
    			</a>
				<a href="javascript:void(0);" 
				   class="remove-from-list pull-right" title="<?php echo t("delete_from_list",1);?>"
				   data-id="{{id}}">
				   <i class="<?php echo get_icon('remove')?>"></i>
				</a>
				<a href="javascript:void(0);" 
				   class="pull-right sticky" title="<?php echo t("stick_it",1);?>"
				   data-id="{{id}}" data-sticky=0>
				   <i class="<?php echo get_icon('pushpin')?>"></i>
				</a>
    		</div>
    	{{/result}}
    	</div>
    	</textarea>
    </div>
</div>

</div>

<?php
$this->headScript()->headScript()->appendFile(
    ASSETS_CDN . "/js/3rdparty/jquery-ui-1.11.1.custom/jquery-ui.min.js");
$this->headScript()->headScript()->appendFile(ASSETS_CDN . "/js/list/order-items.v2.js");
?>
<style>
.connectedSortable li
{
    border : 1px solid #eee;
    padding : 5px;
}
.connectedSortable
{
    border : 2px solid green;
}
</style>