<?php $page = Zend_Registry::get('page');?>
<div class='border-style'>

<ul class='nav nav-pills <?if (!isset($this->horizontalLayout)):?>nav-stacked<?endif;?>'>
	<li <?php if ($page == 'story/index/new') echo "class='active'";?>>
		<a href="/story/new?type=1"><?php echo gen_icon('plus');?>
		<?php if (!isset($this->compactMode)):?> New<?php endif;?></a></li>
	<? if (isset($this->row)) :?>    
		<li <?php if ($page == 'story/index/update' && $this->step == '') echo "class='active'";?>>
			<a href="/story/update<?php if (isset($this->row['id'])) echo "?id=" . $this->row['id'];?>">
			<?php echo gen_icon('edit');?><?php if (!isset($this->compactMode)):?> Update<?php endif;?></a></li>
	
	   
		<li <?php if ($page == 'story/index/update' && $this->step == 'avatar') echo "class='active'";?>>
			<a href="/story/update<?php if (isset($this->row['id'])) echo "?id=" . $this->row['id'];?>&_cl_step=avatar">
			<?php echo gen_icon('picture');?><?php if (!isset($this->compactMode)):?> Avatar<?php endif;?></a></li>
			
		<li>
			<a class='modal_ajax' data-modal-width="900px" href="<?php echo node_link('story', $this->row);?>">
			<?php echo gen_icon('preview');?><?php if (!isset($this->compactMode)):?> View<?php endif;?></a></li>		
			
	<?php endif;?>    
	
	<li <?php if ($page == 'story/index/search') echo "class='active'";?>>
		<a href="/story/search"> <?php echo gen_icon('search');?><?php if (!isset($this->compactMode)):?> Search<?php endif;?></a></li>
    
    <li <?php if ($page == 'story/index/search-comment') echo "class='active'";?>>
	    <a href="/story/search-comment"><?php echo gen_icon('comment');?>
	    <?php if (!isset($this->compactMode)):?> Comments<?php endif;?></a></li>
	
	<li <?php if ($page == 'story/index/category-new' ||
	        $page == 'story/index/category-update' ||
	        $page == 'story/index/categories') echo "class='active'";?>>
	     <a href="/category/index/search?type=story"><?php echo gen_icon('category');?>
	     <?php if (!isset($this->compactMode)):?> Story Categories<?php endif;?></a></li>
</ul>

<div style='min-height:10px;'></div>

</div>