<div class='separator'></div>

<div class='row' >

<?php echo sand_dev_info_phtml(__FILE__);?>

<div class='col-md-12'>
<?php $this->compactMode = 1;?>
<?php $this->horizontalLayout = 1;?>
<?php echo $this->render('index/navbar.phtml');?>
</div>

</div>

<div class='row'>
<div class='col-md-2'>
    <div class='search_form border-style'>
    <?php $this->form->setDisplayInline();
        $this->form->setAttrib('id' , 'search_form');
    ?>
    <?php echo $this->form;?>
    </div>
</div>

<div class='col-md-10'>
    <?php if($this->total > 0) :?>
        <?php echo $this->render("widget/pagination.phtml");?>
    <?php endif;?>
    
    <?php if($this->count > 0) :?>
	
    	<?php //echo $this->render('widget/table.phtml');?>
    	<a href="/story/bulk-delete" id='bulk-delete' class="cl_ajax btn btn-xs btn-danger">
    		<?php echo gen_icon('remove');?> Delete Selected</a>
    	<div class="clear"></div>
    	<br/>
        <table class="table table-striped table-bordered table-condensed">
        	<thead>
        		<tr>
        			<th><input type="checkbox" class="checkall"/></th>
        			<th style='width:60px;'>avatar</th>
        			<th style='width:60px'>Category</th>
        			<th>Name</th>
        			<th style='width:10%;'>Source</th>
        			<th style='width:20%;'>Tags</th>        			
        			<th style='width:60px;'>Status</th>
        			<th style='width:25px;'>Author</th>
        			<th style='width:10px;'>Action</th>
        			
        		</tr>
        	</thead>
        	<tbody>
        		<?php foreach($this->list as $row) :?>
        		<?php 
        		if (!isset($row['avatar']) || $row['avatar'] == '')
        			$row['avatar'] = ASSETS_CDN . '/images/avatar.gif' ;
        		?>
        		<tr id="<?php echo $row['id'];?>">
        			<td>
        				<input type="checkbox" value="<?php echo $row['id'];?>" class="check-item" /></td>
        			<td>
        				<?php 
        				$link = "/media/browse?avatar=1&_cl_ajax=1";
        				$link = "/story/update?id={$row['id']}&_cl_step=avatar";
        				?>
	        			<a
		        			href="<?php echo $link;?>"
		        			 data-modal-width='990px'
		        			 data-modal-iframe='true'
		        			 data-modal-iframe-title='File browser'
		        			 data-id='<?php echo $row['id'];?>'>
	        			
	        			<?php if (isset($row['avatar'])):?>
	        			<img class='img50 thumbnail' src='<?php echo $row['avatar'];?>'/>
	        			<?php else:?>
	        				Update
	        			<?php endif;?>
	        			</a>
        			</td>
        			<td>
						<?php echo $row['category'];?>
        			</td>
        			<td>
	        			<a class='modal_ajax preview_story medium bold' 
		        			data-modal-width="990px"
		        			
		        			href="<?php echo node_link('story',$row);?>">
	        			<?php echo $row['name'];?></a>
	        			    <p class='chapo' style='display:none;'><?php echo $row['chapo'];?></p>
	        			    
	        			<?php if (isset($row['ots'])):?>
	        			<br/>
	        			<span style='font-style:italic;'>
	        			<?php echo date('d/m/Y - h:i A', $row['ots']);?>
	        			</span>
	        			<?php 
	/*        			
	        			<span class='timeago bold' title="<?php echo convert_ts_to_js($row['ots']);?>"></span>
	*/        			
	        			?>
	        			<?php endif;?>
	
	        			<?php if (isset($row['ots'])):?>
	        			
	        			<br/>
	        			Posted:
	        			<span class='timeago bold' title="<?php echo convert_ts_to_js($row['ts']);?>"></span>
	        			<?php endif;?>
        			
        			</td>
        			<td>
	        			<?php if (isset($row['ourl'])):?>
		        			<a target='_blank' href='<?echo $row['ourl'];?>'>
								<?php if (isset($row['source']) && $row['source'] != ''):?>
		        					<?php 
		        					$row['sourceInfo'] = Dao_Node_Source::getInstance()->getNodeFromRedis($row['source']);
		        					?>
		        					<img src="<?php echo $row['sourceInfo']['avatar'];?>" />
		        					<br/>
		        					<?php echo $row['sourceInfo']['slug'];?>
		        				<?php else:?>
			        				<?php echo get_host($row['ourl']);?>
			        			<?php endif;?>
			        			</a>
		        		<?php endif;?>
       				</td>
        			<td>
            			<div>
    	    					<form action='/story/update' class='cl_ajax'>
    							<div style='width:100%;'>
    			    				<input type="text" name="tags" 
    			    				    value='<?php if (isset($row['tags'])) echo json_encode($row['tags']);?>'
    			    				    data-url='/suggest.php?node=tag&addnew=1&' 
    			    				    class="conceptTokens" transformers="tokensJSONStringToArray"></dd>
    							</div>
    							
    							<div>
	    							<input type='hidden' name='_cl_step' value='tags'>
	    							<input type='hidden' name='id' value='<?php echo $row['id'];?>'>
	    							<input type='submit' name='_cl_submit' value='Update' class='btn btn-primary btn-xs pull-right'>
    							</div>
    			    			</form>
    	    			</div>
        			</td>
        			
        			<td>
                        <div class="btn-group">
        			    	<a href="/story/update?id=<?php echo $row['id'];?>&status=0&_cl_step=status"
        			    	class="btn btn-primary btn-xs <?php if($row['status']==0) echo 'active';?> cl_ajax" 
        			    	data-sand-callbacks-metadata="active_button_group">Q.</a>
        			    	<a href="/story/update?id=<?php echo $row['id'];?>&status=1&_cl_step=status"
        			    	class="btn btn-primary btn-xs <?php if($row['status']==1) echo 'active';?> cl_ajax" data-sand-callbacks-metadata="active_button_group">OK</a>
        			    </div>
        			</td>
        			<td>
        				<a href="<?php echo user_link($row['u']);?>" class="user" ><?php echo $row['u']['name'];?></a>
        			</td>
        			<td>
        				<a title="edit" href="/story/update?id=<?php echo $row['id']?>" class="btn btn-default btn-xs">
        					<?php echo gen_icon('edit');?></a>
        				<a title="Delete" href="/story/delete?id=<?php echo $row['id']?>" 
        					class="btn btn-xs btn-danger cl_ajax" data-sand-callbacks-metadata="remove_my_parent:2"
        					data-sand-ajax-confirm='Are you sure you want to permanently delete this item?'
        					>
        					<?php echo gen_icon('remove');?>
        				</a>
        			</td>
        		</tr>
        		<?php endforeach;?>
        	</tbody>
        </table>
    <?php else:?>
    	<h3>No story found</h3>
    <?php endif;?>
</div>

</div>

<style>
.search_form dd label
{
	font-weight:normal !important;
}		        					
</style>