<?php echo sand_dev_info_phtml(__FILE__);?>
<?php 
$top10 = Dao_Node_Story::getInstance()->getByList('home:top1');
?>

<div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Tin nóng</h3>
      </div>
      <div class="panel-body">

	<?php foreach ($top10 as $t):?>
	 <div>
	<i style='font-size:80%;' class='text-muted <?php echo get_icon('chevron-right');?>'></i> 
		<a href='<?php echo node_link('story', $t);?>'><?php echo $t['name']?></a>
		 <span class='text-muted' style='font-size:80%;'><?php echo date('d/m/Y', $t['ts']);?></span>
	 </div>
	<?php endforeach;?>
	</div>
</div>
