<?php echo sand_dev_info_phtml(__FILE__);?>
<?php 
//TODO: thuat toan hien thi top news, lam the nao de cac muc hien thi khac nhau
/*
 *
giua left,right,top1,top2 ( khong bi trung noi dung)
*/
	$list = $this->list;
	$top1 = $list['home:top1'];
	$top2 = $list['home:top2'];
	$left = $list['home:left'];
	$right = $list['home:right'];
	$qc = $list['home:qc'];
	$renderMode = isset($this->renderMode) ? $this->renderMode : '';
?>
<div class="row">
    <div class='col-md-9' id='top-section'>
    	<?php //home:hot_left?>
    	<div class="row" id="box_news_top">
        	<div class='col-md-9 justify' id='top1'>
        	   <?php if ($renderMode == 'fake'):?>
        	   <h3>top1</h3>
        	   <?php endif;?>
        	   
        		<div class='top1-avatar'>
        			<a href='<?php echo $top1[0]['link'];?>'>
        				<img class='top1' src='<?php echo display_avatar($top1[0]['avatar'], 'medium');?>'>
        			</a>
        		</div>
        		<div class='top1_news_title medium-large bold'>
        			<a class='highlight' href='<?php echo $top1[0]['link'];?>'><?php echo $top1[0]['name']?></a>
        		</div>
        		<div class='top1-chapo'>
        			<?php echo $top1[0]['chapo'];?>
        		</div>
        		<?php if (count($top1) > 1):?>
        		<div class='top1-related'>
    				<div><a class='dimmed' href='<?php echo $top1[1]['link'];?>'><?php echo $top1[1]['name'];?></a></div>
        		</div>
        		<?php endif;?>
        	</div>
        	
        	<div class='col-md-3' id='top2'>
        	   <?php if ($renderMode == 'fake'):?>
        	   <h3>top2</h3>
        	   <?php endif;?>
        	<?php if (isset($list['home:top2'])):?>
        		<div id='top2-ul'>
        			<b>Latest news</b>
        			<ul class='no-margin no-bullet'>
        			<?php foreach ($top2 as $i => $item):?>
        				<li >
        					<?php if ($i == 0):?>
        					<div class=''>
        						<div >
        							<a class='dimmest' href='<?php echo $item['link'];?>'><?php echo $item['name'];?></a><br/>
        							<span class='timeago dimmed' title="<?php echo convert_ts_to_js($item['ts']);?>"></span>
        						</div>
        					
        					</div>
        					
        					<?php elseif ($i < 6):?>
        					<div>
        						<a class='dimmest' href="<?php echo $item['link'];?>">
        							<?php echo $item['name'];?>
        						</a> <br/>
        						<span class='dimmed timeago' title="<?php echo convert_ts_to_js($item['ts']);?>"></span>
        					</div>
        					<?php endif;?>
        				</li>
        			<?php endforeach;?>
        			</ul>
        		</div>
        	
        	<?php endif;?>
        	</div>
    
    	</div>
    	
    	<div class="row">
        	<div class='col-md-6' id='home_left'>
        	      <?php if ($renderMode == 'fake'):?>
        	   <h3>left</h3>
        	   <?php endif;?>
        		<?php foreach ($left as $item):?>
        			<div class="one_news">
        			     <div class="title_news">
        			         <a class="txt_link" href='<?php echo $item['link'];?>'><?php echo $item['name'];?></a>
        			     </div>
        			     <div class="row">
        			         <?php if($item['avatar'] != DEFAULT_AVATAR_URL):?>
        			         <div class="col-md-4">
        			             <a href='<?php echo $item['link'];?>'>
        			                 <img alt="" class="img-responsive" src="<?php echo $item['avatar'];?>">
    			                 </a>
        			         </div>
        			         <?php endif;?>
        			         <div class="<?php if($item['avatar'] != DEFAULT_AVATAR_URL): ?>
        			                     <?php   echo 'col-md-8'; else : echo "col-md-12"; endif;?>  ">
        			             <?php echo $item['chapo'];?>
        			         </div>
        			     </div>
        			</div>
        		<?php endforeach;?>
            </div>
            <div class='col-md-6' id='home_right'>
                   <?php if ($renderMode == 'fake'):?>
        	   <h3>right</h3>
        	   <?php endif;?>
        		<?php foreach ($right as $item):?>
        			<div class="one_news">
        			     <div class="title_news">
        			         <a class="txt_link" href='<?php echo $item['link'];?>'><?php echo $item['name'];?></a>
        			     </div>
        			     <div class="row">
        			         <?php if($item['avatar'] != DEFAULT_AVATAR_URL):?>
        			         <div class="col-md-4">
        			             <a href='<?php echo $item['link'];?>'>
        			                 <img alt="" class="img-responsive" src="<?php echo $item['avatar'];?>">
    			                 </a>
        			         </div>
        			         <?php endif;?>
        			         <div class="<?php if($item['avatar'] != DEFAULT_AVATAR_URL): ?>
        			                     <?php   echo 'col-md-8'; else : echo "col-md-12"; endif;?>  ">
        			             <?php echo $item['chapo'];?>
        			         </div>
        			     </div>
        			</div>
        		<?php endforeach;?>
            </div>
        </div>
    </div>
    <div class='col-md-3' id='qc'>
    	   <?php if ($renderMode == 'fake'):?>
        	   <h3>qc</h3>
        	   <?php endif;?>
    	<div>
    		<ul>
    		<?php foreach ($qc as $item):?>
    			<li><a class='dimmed' href='<?php echo $item['link'];?>'><?php echo $item['name'];?></a></li>
    		<?php endforeach;?>
    		</ul>
    	</div>
    </div>
</div>
<div class='row'>
	<div class='col-md-12'>
		<hr/>
	</div>
</div>
