<?php 
if (!$isPreview)
{ 
	$class1= 'col-md-7';
	$class2= 'col-md-2';
	$class3= 'col-md-3';
}
else 
{
	$class1= 'col-md-12';
	$class2= '';
	
}
;?>

<div class='row'>
<div class='<?echo $class1;?>'>
    <?php if (get_value('tags__slug')):?>
        <?php $tagSlug = get_value('tags__slug');
            $r = Dao_Node_Tag::getInstance()->findOne(array('slug' => $tagSlug));
            if($r['success'])
            {
                $tag = $r['result'];
            ?>
            <h3>Topic: <?php Echo $tag['name'];?></h3>
            <div class='well'>
            <?php echo $tag['content'];?>
            </div>
            <?php 
            }
        ?>
    <?php endif;?>
    <?php if($this->count > 0) :?>
    <div>
        <?php $page = get_value('page', 1);
            $perpage = get_value('items_per_page', 10);
        ?>
		<?php foreach($this->list as $i => $row) :?>
		    <?php $data = $row;?>
        	<div>
        		<div>
	    		    <a class='news-heading' href='<?php echo node_link('story', $row);?>' >
	                    <?php if (isset($data['name'])):?>
	                     <?php echo ($page - 1)* $perpage + $i + 1;?>. <?php echo $data['name'];?>
	                    <?php endif;?>
	                    </a> 
	                <span style='float:right;font-style:italic;'>  
	                    <?php echo date('d/m/Y - h:i A', $row['ots']);?>
	                    </span>    
        		</div>
                
                <div>
                    <div>
            		<?php if (isset($data['avatar']) && $data['avatar'] != ''):?>
                    <img style='float:left; padding: 0px 10px 10px 2px;width:100px;' src='<?php echo $data['avatar'];?>'>
                    <?php endif;?>
                        
                        <?php if (isset($data['chapo'])):?>
                        <div class=''>
                        <?php echo $data['chapo'];?>.                     
                        </div>
                        <?php endif;?>
                     </div>

                 </div>
    		</div>
    		<div style='clear:both;min-height:10px;'></div>
		<?php endforeach;?>
    </div>
    <div>
    <?php if($this->total > 0) :?>
        <?php echo $this->render("widget/pagination.phtml");?>
    <?php endif;?>
    </div>
    
    <?php else:?>
    <div class='alert alert-success'>
    Oops! No news in this category
    </div>
    <?php endif;?>
</div>    

<div class='<?php echo $class2;?>' style='padding-left:0px;'>
	<?php echo $this->render('nga/home-top-news.phtml');?>
</div>

<div class='<?php echo $class3;?>' style='padding-left:0px;'>
	<?php echo $this->render('nga/right-menu.phtml');?>
</div>

</div>
