<?php echo sand_dev_info_phtml(__FILE__);?>
<?php 
	$row = $this->row;
	if($row == null);
	   $this->renderScript
	//TODO HOTTAG
?>
<div class="row">
    <div class="col-md-9">
        <div class="row" id="box_news_top">
        	<div class='col-md-9 justify' id='top1'>
        		<div class='top1-avatar'>
        			<a href='<?php echo node_link('story', $row[0]);?>'>
        				<img class='top1' src='<?php echo display_avatar($row[0]['avatar'], 'medium');?>'>
        			</a>
        		</div>
        		<div class='top1_news_title medium-large bold'>
        			<a class='highlight' href='<?php echo node_link('story', $row[0]);?>'>
        			<?php echo $row[0]['name']?></a>
        		</div>
        		<div class='top1-chapo'>
        			<?php echo $row[0]['chapo'];?>
        		</div>
        		<?php if (count($top1) > 1):?>
        		<div class='top1-related'>
    				<div><a class='dimmed' href='<?php echo node_link('story', $row[1]);?>'>
    				<?php echo $row[1]['name'];?></a></div>
        		</div>
        		<?php endif;?>
        	</div>
        	
        	<div class='col-md-3' id='top2'>
        	<?php if (isset($list['home:top2'])):?>
        		<div id='top2-ul'>
        			<b>Latest news</b>
        			<ul class='no-margin no-bullet'>
        			<?php foreach ($top2 as $i => $item):?>
        				<li >
        					<?php if ($i == 0):?>
        					<div class=''>
        						<div >
        							<a class='dimmest' href='<?php echo $item['link'];?>'><?php echo $item['name'];?></a><br/>
        							<span class='timeago dimmed' title="<?php echo convert_ts_to_js($item['ts']);?>"></span>
        						</div>
        					
        					</div>
        					
        					<?php elseif ($i < 6):?>
        					<div>
        						<a class='dimmest' href="<?php echo $item['link'];?>">
        							<?php echo $item['name'];?>
        						</a> <br/>
        						<span class='dimmed timeago' title="<?php echo convert_ts_to_js($item['ts']);?>"></span>
        					</div>
        					<?php endif;?>
        				</li>
        			<?php endforeach;?>
        			</ul>
        		</div>
        	
        	<?php endif;?>
        	</div>
    
    	</div>
        <div class='col-md-8' id='tag_main'>
    		<?php foreach ($row as $item):?>
    			<div class="one_news">
    			     <div class="title_news">
    			         <a class="txt_link" href='<?php echo node_link('story',$item);?>'><?php echo $item['name'];?></a>
    			     </div>
    			     <div class="row">
    			         <?php if($item['avatar'] != DEFAULT_AVATAR_URL):?>
    			         <div class="col-md-4">
    			             <a href='<?php echo node_link('story',$item);?>'>
    			                 <img alt="" class="img-responsive" src="<?php echo $item['avatar'];?>">
    		                 </a>
    			         </div>
    			         <?php endif;?>
    			         <div class="<?php if($item['avatar'] != DEFAULT_AVATAR_URL): ?>
    			                     <?php   echo 'col-md-8'; else : echo "col-md-12"; endif;?>  ">
    			             <?php echo $item['chapo'];?>
    			         </div>
    			     </div>
    			</div>
    		<?php endforeach;?>
        </div>
    </div>
    <div class='col-md-3' id='qc'>
    	<div id='qc'>
    	   quang cao
    	</div>
    </div>
</div>
<div class='row'>
	<div class='col-md-12'>
		<hr/>
	</div>
</div>
