<?php 
$list = $this->list;
$left = $list['category:left'];
?>
<?php foreach ($left as $item):?>
	<div class="one_news">
	     <div class="title_news">
	         <a class="txt_link" href='<?php echo $item['link'];?>'><?php echo $item['name'];?></a>
	     </div>
	     <div class="row">
	         <?php if($item['avatar'] != DEFAULT_AVATAR_URL):?>
	         <div class="col-md-4">
	             <a href='<?php echo $item['link'];?>'>
	                 <img alt="" class="img-responsive" src="<?php echo $item['avatar'];?>">
                 </a>
	         </div>
	         <?php endif;?>
	         <div class="<?php if($item['avatar'] != DEFAULT_AVATAR_URL): ?>
	                     <?php   echo 'col-md-8'; else : echo "col-md-12"; endif;?>  ">
	             <?php echo $item['chapo'];?>
	         </div>
	     </div>
	</div>
<?php endforeach;?>