<?php 
	$list = $this->list;
	$top1 = $list['category:top1'];
	?>
<div class='top1-avatar'>
        			<a href='<?php echo $top1[0]['link'];?>'>
        				<img class='top1' src='<?php echo display_avatar($top1[0]['avatar'], 'medium');?>'>
        			</a>
        		</div>
        		<div class='top1_news_title medium-large bold'>
        			<a class='highlight' href='<?php echo $top1[0]['link'];?>'><?php echo $top1[0]['name']?></a>
        		</div>
        		<div class='top1-chapo'>
        			<?php echo $top1[0]['chapo'];?>
        		</div>
        		<?php if (count($top1) > 1):?>
        		<div class='top1-related'>
    				<div><a class='dimmed' href='<?php echo $top1[1]['link'];?>'><?php echo $top1[1]['name'];?></a></div>
        		</div>
        		<?php endif;?>